#+TITLE: NumPy - Learning some basics
#+DESCRIPTION: NumPy - Learning some basics
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:nil ^:{} toc:1

* Introduction
So, my mentor gave me my first task to learn some stuff around NumPy, Panda, and Scikit-Learn until Sunday (today is Thursday).
+ My mentor is [[https://scholar.google.com/citations?user=cHCDiIYAAAAJ][Dr. Abhijit Sen]], and we are starting research through the project [[https://www.ndeavours.org/][Ndeavours]]
+ Keep tuned for updates into what we are doing - I don't know yet because we just started, but it will have something to do with AI.

* What is NumPy?
+ A multi-dimensional array library, meaning you can use it to store all sorts of data, in 1D arrays up to 3D arrays (I guess you could go more, but I don't know if it's true)
** NumPy vs Lists
+ Lists are slow and NumPy fast
+ NumPy uses Fixed Type -> it stores all data into a 32 bit memory (int32), and you can specify other bit values for saving (int16, int8 for example)
+ Lists uses a built-in inttype for python that contains four different things (object value, object type, reference count, and size)
*** Representing 5
+ So as an example, 5 that can be read as 00000101 in bynary is represented with
+ 3 empty bytes + 00000101 in NumPy
+ 3 int64 + 3 empty bytes + 00000101 in Lists
+ The difference in memory is huge!
*** Takeaway
+ NumPy is faster to read less bytes of memory
+ No type checking when interating through objects
+ NumPy also utilizes contiguous memory (not gonna explain it here)
*** The difference in utilzation
+ In Lists you can do Insertion, deletion, appending, concatenation, etc.

~a = [1,3,5]~
~b = [1,2,3]~
~a*b = ERROR~

+ In NumPy you can do Insertion, deletion, appending, concatenation, etc + Lost More

~a = np.array([1,3,5])~
~b = np.array([1,2,3])~
~a*b = np.array([1,6,15])~

** Applications
+ A MATLAB Replacement (maybe)
+ Plotting (Matplotlib)
+ Backend (Pandas, Connect 4, Digital Photography) -> Guess I will be learning it primarly for Pandas
+ Machine Learning -> Guess I will be learning it for this reason

* Some code I followed along with
#+BEGIN_SRC
#!/usr/bin/env python3

# Load in NumPy (remember to pip install numpy first)
import numpy as np

# The Basics
a = np.array([1,2,3], dtype='int16' )
print(a)
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)
# Get Dimension
print(a.ndim)
# Get Shape
print(b.shape)
# Get Type
print(a.dtype)
print(b.dtype)
# Get Size
print(a.itemsize)
print(b.itemsize)
# Get total size
print(a.size * a.itemsize) # or using:
print(a.nbytes)

#+END_SRC

#+BEGIN_SRC
#!/usr/bin/env python3

# Load in NumPy
import numpy as np


# Accessing/Changing specific elements, rows, columns, etc
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

# Get a specific element [ r, c ]
print(a[1,5])
# Get a specific row
print(a[0, :])
# Get a specific collum
print(a[:, 2])
#Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:6:2])
#Changing an element
a[1,5] = 20
print(a)
#Changing a specific collum
a[:,2] = 5
print(a)
# 3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
# Get specific element (work outside in)
print(b[0,1,1])
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)
#+END_SRC

#+BEGIN_SRC
#!/usr/bin/env python3

import numpy as np

#All 0s matrix
print(np.zeros(5))
#or
print(np.zeros((2,3)))
#All 1s matrix
print(np.ones((4,2,2), dtype='int32'))
#Any other number
print(np.full((2,2) ,99))
# Any other number (full_like)
# Let's suppose you created this array bellow
a = np.array([1,2,3,4])
# Now you can create an array with any other number and use the same shape as your last array
print(np.full_like(a,4))
# Random decimal numbers
print(np.random.rand(4,2))
# Random Integer values
print(np.random.randint(-4,8, size=(3,3)))
# The Identity matrix
print(np.identity(5))
# Repeat array a few times
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)
#+END_SRC


#+BEGIN_SRC
#!/usr/bin/env python3

import numpy as np

# Initialize this 5x5 array (Idk, it is an image)
a = np.array([[1,1,1,1,1]])
b = np.array([[1,0,0,0,1]])
c = np.array([[1,0,9,0,1]])
r2 = np.repeat(b,1, axis=0)
r1 = np.repeat(a,1, axis=0)
print(a)
print(b)
print(c)
print(r2)
print(r1)

# The solution
print("\nNow the solution: \n")
output = np.ones((5,5))
#print(output)

z = np.zeros((3,3))
z[1,1] = 9
#print(z)

output[1:4,1:4] = z
print(output)
#+END_SRC


#+BEGIN_SRC
#!/usr/bin/env python3

import numpy as np

# Copy it like this
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
#+END_SRC


+ The rest are jupyter notebooks, which are very bad to paste here :(

** Code I followed with codemy.com
#+BEGIN_SRC
#!/usr/bin/env python3

import numpy as np

list1 = [1,2,3,4,5]
#print(list1)
#print(list1[0])

list2 = ["John Elder", 41, list1, True]
#print(list2)

# Numpy - Numeric Python
# ndarray = n-dimensional array

np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1.shape)

# Range
np2 = np.arange(10)
print(np2)

# Step
np3 = np.arange(0,10,2)
print(np3)

# Zeros
np4 = np.zeros(10)
print(np4)

# Multidimensional zeros
np5 = np.zeros((2,10))
print(np5)

# Full
np6 = np.full((10), 6)
print(np6)

# Multidimensional full
np7 = np.full((2,10), 6)
print(np7)

# Convert Python lists to np
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)
print(np8[0])
#+END_SRC

#+BEGIN_SRC
#!/usr/bin/env python3

import numpy as np

# Slicing Numpy Arrays
np1 = np.array([1,2,3,4,5,6,7,8,9])

# Return 2,3,4,5
print(np1[1:5])

# Return from something till the end of the array
print(np1[3:])

# Return Negative Slices -> The last element is negative 1
print(np1[-3:-1])

# Steps
print(np1[1:5]) # 2,3,4,5 (2 to 5)
print(np1[1:5:2]) # 2,4 (2 to 5 in steps of 2)

# Setps on the entire array
print(np1[::2]) # Entire array from beginning to end (::) in steps of 2
print(np1[::3]) # Entire array from beginning to end (::) in steps of 3

# Slice a 2-d array
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# Pull out a single item
print(np2[1,2]) # The first d is the 0th item, the second d is the 1th item (the 2 means the 2nd element)

# Slice a 2-d array (prints 2,3)
print(np2[0:1, 1:3])

# Slice from both rows (prints 2,3 and 7,8)
print(np2[0:2, 1:3])
#+END_SRC

#+BEGIN_SRC
#!/usr/bin/env python3

import numpy as np

# Numpy Universal Function
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print (np1)

# Square root of each element
#print(np.sqrt(np1))

# Absolute Value
#print(np.absolute(np1))

# Exponents
#print(np.exp(np1))

# Min/Max
#print(np.max(np1))
#print(np.min(np1))

# Sign positive or negative
#print(np.sign(np1))

# Trig sin cos log
#print(np.sin(np1))
#print(np.cos(np1))
#print(np.log(np1))
#+END_SRC


#+BEGIN_SRC
#!/usr/bin/env python3

import numpy as np

# Code Vs. View
np1 = np.array([0,1,2,3,4,5])

# Create a view
# It is a copy of the original, but it still gets affected by changed in the original
# If the "view" gets changed, the original also gets changed -> It is both ways
np2 = np1.view()

print(f'Original NP1 {np1}')
print(f'Original NP2 {np2}')

np2[0] = 41

print(f'Changed NP1 {np1}')
print(f'Original NP2 {np2}')

# Create a Copy
np2 = np1.copy()

print(f'Original NP1 {np1}')
print(f'Original NP2 {np2}')

np2[0] = 41

print(f'Changed NP1 {np1}')
print(f'Original NP2 {np2}')
#+END_SRC


#+BEGIN_SRC
#!/usr/bin/env python3
import numpy as np

# 1-d
#np1 = np.array([1,2,3,4,5,6,7,8,9,10])
#for x in np1:
#    print(x)


# 2-d Array
#np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
#for x in np2:
#    # Print rows
#    #print(x)
#    for y in x:
#        print(y)

# 3-d Array
np3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
'''
for x in np3:
    #print(x)
    for y in x:
        #print(y)
        for z in y:
            print(z)
'''

# Use np.nditer()
for x in np.nditer(np3):
    print(x)
#+END_SRC


#+BEGIN_SRC
#!/usr/bin/env python3
import numpy as np

# Create 1-D Numpy Array and Get Shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)
print(np1.shape)

# Create 2-D Array and get Shape, (rows/columns-elements)
#np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
#print(np2)
#print(np2.shape)

# Reshape 2-D
#np3 = np1.reshape(3,4)
#print(np3)
#print(np3.shape)

# Reshape 3-D
np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)

# Flatten to 1-D
np5 = np4.reshape(-1) # Sets it back to 1-D
print(np5)
print(np5.shape)
#+END_SRC


#+BEGIN_SRC
#!/usr/bin/env python3
import numpy as np

# np.sort () Numerical
np1 = np.array([6,7,4,9,0,2,1])
#print(np1)
#print(np.sort(np1))

# Alphabetical
#np2 = np.array(["John", "Tina", "Aaron", "Zed"])
#print(np2)
#print(np.sort(np2))

# Booleans T/F
#np3 = np.array([True, False, False, True])
#print(np3)
#print(np.sort(np3))

# Return a copy not changing the original
#print(np1)
#print(np.sort(np1))
#print(np1)

# 2-d
np4 = np.array([[6,7,1,9],[8,3,5,0]])
print(np4)
print(np.sort(np4))
#+END_SRC


#+BEGIN_SRC
#!/usr/bin/env python3
import numpy as np

# Search
np1 = np.array([1,2,3,4,5,6,7,8,9,10, 3])

#x = np.where(np1 == 3)
#print(np1)
#print(x[0])
#print(np1[x[0]])

# Return even items
#y = np.where(np1 % 2 == 0)
#print(np1)
#print(y[0])
#print(np1[y[0]])

# Return odd items
z = np.where(np1 % 2 == 1)
print(np1)
print(z[0])
print(np1[z[0]])
#+END_SRC


#+BEGIN_SRC
#!/usr/bin/env python3

import numpy as np

# Filtering Numpy Arrays With Boolean Index Lists

np1 = np.array([1,2,3,4,5,6,7,8,9,10])

#x = [True, True, False, False, False, False, False, False, False, False]
#print(np1)
#print(np1[x])

'''
filtered = []
for thing in np1:
    if thing % 2 == 0:
        filtered.append(True)
    else:
        filtered.append(False)

print(np1)
print(filtered)
print(np1[filtered])
'''

# Shortcut!
filtered = np1 % 2 == 0
print(np1)
print(filtered)
print(np1[filtered])
#+END_SRC

* Resources
** Videos
+ [[https://www.youtube.com/watch?v=QUT1VHiLmmI][Python NumPy Tutorial for Beginners]]
+ Playlist: [[https://youtube.com/playlist?list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK][Numpy For Machine Learning]]
