#+TITLE: Eficiência energética
#+DESCRIPTION: Eficiência energética - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Sistema de Avaliação
+ P1 -> 10,0 (22/8)
+ P2 -> 10,0
\[N1 = P1+P2\]
+ P3 -> 10,0
+ P4 -> 10,0
\[N1 = P3+P4\]
+ Rec 1 - Substituirá N1
+ Rec 2 - Susbtituirá N2
+ 15h/a presencial + 15h/a assíncrona

* Consumo de energia elétrica ou simplesmente energia
\[C = P\times \Delta t\]
+ P = Potência ativa (W), mas podem aparecer outros tipos de potência
+ \[\Delta t\] intervalo de tempo (h)

* Rendimento
\[\eta (\%) = \frac{Po}{Pi}\times 100 (\%)\]
\[Pi = \Sigma perdas + Po\]
** Eficiência luminosa:
\[E.L = {\Phi_L} = Fluxo luminoso da lâmpada (lúmens)\]
\[P = Pot. da lâmpada (W)\]

* Faturamento de Energia Elétrica
** Grupo A
+ Faturamento de consumo e demanda (kWh);
+ Unidade consumidora com transformador(es);
+ Possibilidade de cobrança em horários diferenciados;
** Grupo B
+ Faturamento somente de consumo (kWh);
+ Atendimento em BT;
** Demanda medida, contratada e faturada
+ Medida (DM): Registro da média das potência em um intervalo de 15 minutos. Em um mês (30 dias) serão registradas 4x24x30 = 2880 demandas
+ Controlada (DC): Informada à concessionária para fins de faturamento e análise de disponibilidade do sistma elétrico.
+ Faturada (DF): É a maior entre a medida e a contratada.

* Faturamento de Demanda
+ Demandas medida, contratada e faturada
+ A faturada é a maior entre a medida e a contratada
+ Demanda ultrapassada: valor superior à 5\% da contratada.
+ Faturamento da demanda de ultrapassagem: \[FDU = (DM - DC)\times 2\times TD\]

** Exercício
+ Uma unidade consumidora possui um contrato de demanda de 200kW. Calcule o faturamento para cada situação:
a) DM = 180 kW
\[FD = 200x30 = 6000\]
b) DM = 202 kW
+ Dentro dos 5\% de tolerância
\[FD = 202\times 30 = 6060\]
c) DM = 210 kW
+ Limite dos 5\% de tolerância
\[FD = 210\times 30 = 6300\]
a) DM = 215 kW
\[FD = (200x30) + (15x2x30) = 6900\]
TD = 30 reais por kW

+ Em relação à questão anterior qual poderia ser a demanda contratada para não ocorre ultrapassagem de demanda?
\[DC\times 1,05 = DM\]
\[DC\times 1,05 = 215\]
\[DC \approx 205 kW\]

* 15/8
+ Modalidade tarifárias (Grupo A) - Faturamento
** Verde
+ Demanda única (kW)
+ Consumo no Horário de Ponta (kWh)
+ Consumo no Horário Fora de Ponta (kWh)
** Azul
+ Demanda no Horário de Ponta (kW)
+ Demanda no Horário Fora de Ponta (kW)
+ Consumo no Horário de Ponta (kWh)
+ Consumo no Hoário Fora de Ponta (kWh)
** Horário de ponta
+ 3h consecutivas de segunda a sexta feira, com exceção de feriados nacionais. Em MS -> 17h30 até 20h30

** Exemplo: Modalidade Verde
+ DMp = 30kW
+ DC = 100kW
+ Cfp = 25000kWh
+ TCp = R$ 3,44/kWh

+ DMfp = 120kW
+ Cp = 1000kWh
+ TD = R$40,29/kW
+ TCfp = R$ 0,48/kWh

+ Faturamento Total (FT) = (CpxTCp) + (CfpxTCfp) + (DCxTD) + (DMfp-DCx2xTD) = (1000x3,44) + (25000x0,48) + (100x40,29) + (20x2x40,29) = R$ 21080,6

* Prof
[8/28, 6:41 PM] Luis Spengler: XI - demanda: média das potências elétricas ativas ou reativas, injetada ou requerida do sistema
elétrico de distribuição durante um intervalo de tempo especificado;
XII - demanda contratada: demanda de potência ativa a ser obrigatória e continuamente
disponibilizada pela distribuidora no ponto de conexão, conforme valor e período de vigência fixados em
contrato, em kW (quilowatts);
XIII - demanda medida: maior demanda de potência ativa injetada ou requerida do sistema
elétrico de distribuição pela carga ou geração, verificada por medição e integralizada em intervalos de 15
minutos durante o período de faturamento, em kW (quilowatts);
[8/28, 6:41 PM] Luis Spengler: RESPOSTA DA 14: XXXVIII - posto tarifário: período em horas para aplicação das tarifas de forma diferenciada ao
longo do dia, considerando a seguinte divisão:
a) posto tarifário ponta: período composto por 3 horas diárias consecutivas definidas pela
distribuidora considerando a curva de carga de seu sistema elétrico, aprovado pela ANEEL para toda a
área de concessão ou permissão, não se aplicando aos sábados, domingos, terça-feira de carnaval, sextafeira da Paixão, Corpus Christi e aos feriados nacionais dos dias 1º de janeiro, 21 de abril, 1º de maio, 7 de
setembro, 12 de outubro, 2 de novembro, 15 de novembro e 25 de dezembro;
b) posto tarifário intermediário: período de duas horas, sendo uma hora imediatamente anterior
e outra imediatamente posterior ao horário de ponta, aplicado apenas para o grupo B; e
c) posto tarifário fora de ponta: período composto pelo conjunto das horas diárias consecutivas
e complementares àquelas definidas nos postos ponta e, para o grupo B, intermediário
[8/28, 6:41 PM] Luis Spengler: XVI - energia elétrica ativa: aquela que pode ser convertida em outra forma de energia, em kWh
(quilowatts-hora);
XVII - energia elétrica reativa: aquela que circula entre os diversos campos elétricos e
magnéticos de um sistema de corrente alternada sem produzir trabalho, em kvarh (quilovolt-ampèrereativo-hora);
[8/28, 6:41 PM] Luis Spengler: Das Modalidades Tarifárias Horárias
...Art. 213. A modalidade tarifária horária verde é caracterizada por:
I -1 (uma) tarifa para a demanda, sem segmentação horária;
II - 1 (uma) tarifa para o consumo de energia elétrica para o posto tarifário ponta; e
III - 1 (uma) tarifa para o consumo de energia elétrica para o posto tarifário fora de ponta.
Art. 214. A modalidade tarifária horária azul é caracterizada por:
I - 1 (uma) tarifa para a demanda para o posto tarifário ponta;
II - 1 (uma) tarifa para a demanda para o posto tarifário fora de ponta;
III - 1 (uma) tarifa para o consumo de energia elétrica para o posto tarifário ponta; e
IV - 1 (uma) tarifa para o consumo de energia elétrica para o posto tarifário fora de ponta.
[8/28, 6:41 PM] Luis Spengler: XXIII - grupo A: grupamento composto de unidades consumidoras com conexão em tensão
maior ou igual a 2,3 kV, ou atendidas a partir de sistema subterrâneo de distribuição em tensão menor que
2,3 kV, e subdividido nos seguintes subgrupos:
a) subgrupo A1: tensão de conexão maior ou igual a 230 kV;
b) subgrupo A2: tensão de conexão maior ou igual a 88 kV e menor ou igual a 138 kV;
c) subgrupo A3: tensão de conexão igual a 69 kV;
d) subgrupo A3a: tensão de conexão maior ou igual a 30 kV e menor ou igual a 44 kV;
e) subgrupo A4: tensão de conexão maior ou igual a 2,3 kV e menor ou igual a 25 kV; e
f) subgrupo AS: tensão de conexão menor que 2,3 kV, a partir de sistema subterrâneo de
distribuição;
XXIV - grupo B: grupamento composto de unidades consumidoras com conexão em tensão
menor que 2,3 kV e subdividido nos seguintes subgrupos:
a) subgrupo B1: residencial;
b) subgrupo B2: rural;
c) subgrupo B3: demais classes; e
d) subgrupo B4: Iluminação Pública;

[8/28, 6:41 PM] Luis Spengler: DE CÁLCULOS CAIRÁ SOMENTE AS MODALIDADES AZUL E VERDE, DO GRUPO A. E A CONVENCIONAL DO GRUPO B (SÓ FATURA CONSUMO).
[8/28, 6:41 PM] Luis Spengler: Toda esses artigos com estruturas e definições foram explicados em sala. É a base para a lista. Estudem o que está no caderno e o que está na lista. Bom domingo e bons estudos!
[8/28, 6:41 PM] Luis Spengler: CORRIGIDO:

1) Defina Carga Instalada (kW).

“É a soma das potências nominais, dos equipamentos elétricos instalados na unidade consumidora, em condições de entrar em funcionamento, expressa em quilowatts (kW).” (NDU 2 - Energisa)

2) Defina Demanda (kW).

“É a média das potências elétricas, ativas ou reativas, solicitadas ao sistema elétrico, durante um intervalo de tempo especificado.”

3) Uma residência possui consumo médio mensal de 350 kWh. Calcule seu faturamento, considerando a tarifa de consumo igual a R$ 1,01 / kWh.

FT = 350 x 1,01 = R$ 353,50

4) Uma unidade consumidora enquadrada na modalidade tarifária verde possui demanda contratada igual a 120 kW. A tarifa é de R$ 40,03 / kW. Calcule o faturamento de demanda para as 5 situações:

a) Demanda medida (kW) = 100 kW; FD = 120 x 40,03 = R$ 4.803,60
b) Demanda medida (kW) = 125 kW;FD = 125 x 40,03 = R$ 5.003,75
c) Demanda medida (kW) = 128 kW; FD =  (120 x 40,03) + (8 x 2 x 40,03) = R$ 5.444,08
d) Demanda medida (kW) = 90 kW; FD = 120 x 40,03 = R$ 4.803,60
e) Demanda medida (kW) = 80 kW. FD = 120 x 40,03 = R$ 4.803,60

5) Qual seria o contrato de demanda mais conveniente considerando o histórico de demandas medidas apresentado na questão 4? DC = 96 kW (considerando cobrança total realizada nas 5 situações). Mesmo pagando algumas ultrapassagens de demandas, compensaria as demandas não utilizadas.

6) Considerando o contrato da questão 5, um consumo no horário de ponta igual a 5000 kWh e um consumo no horário fora de ponta de 30000 kWh, calcule o faturamento total para uma demanda medida de 105 kW. Tarifa de consumo no horário de ponta: R$ 3,44 / kWh. Tarifa de consumo no horário fora de ponta: R$ 0,48 / kWh.
FT = (5000 x 3,44) + (30000 x 0,48) + (96 x 40,03) + [(105 – 96) x 2 40,03] = R$ 36.163.42

7) Explique como é feito o faturamento de energia e demanda na modalidade tarifária azul. Como é feito o faturamento de demandas? (Explique citando os tipos de demanda que são levadas em consideração, além de tolerâncias existentes). Como é feito o faturamento de consumos?

Faturamento de demandas: Um contrato para o horário de ponta e outro para o horário fora de ponta. Entre a medida e a contratada, fatura-se a maior. Se a medida for 5% maior que a contratada, fatura-se a demanda contratada multiplicada pela tarifa, mais o que ultrapassou multiplicado pelo dobro da tarifa.

Faturamento de consumos: Um faturamento para o horário de ponta e outro para o horário fora de ponta.
[8/28, 6:48 PM] Luis Spengler: RESPOSTA DA 14: XXXVIII - posto tarifário: período em horas para aplicação das tarifas de forma diferenciada ao
longo do dia, considerando a seguinte divisão:
a) posto tarifário ponta: período composto por 3 horas diárias consecutivas definidas pela
distribuidora considerando a curva de carga de seu sistema elétrico, aprovado pela ANEEL para toda a
área de concessão ou permissão, não se aplicando aos sábados, domingos, terça-feira de carnaval, sextafeira da Paixão, Corpus Christi e aos feriados nacionais dos dias 1º de janeiro, 21 de abril, 1º de maio, 7 de
setembro, 12 de outubro, 2 de novembro, 15 de novembro e 25 de dezembro;
b) posto tarifário intermediário: período de duas horas, sendo uma hora imediatamente anterior
e outra imediatamente posterior ao horário de ponta, aplicado apenas para o grupo B; e
c) posto tarifário fora de ponta: período composto pelo conjunto das horas diárias consecutivas
e complementares àquelas definidas nos postos ponta e, para o grupo B, intermediário

* Medidas de Eficiência para reduzir custos no horário de ponta
+ Carga horária mensal: 22x3 = 66h (aprox)
** Deslocamento ou redução de cargas
+ Parar de utilizar cargas em horários de ponto
** Utilização de grupo motor gerador a Diesel
+ Analisar inverstimento inicial no equipamento e instalações;
+ Analisar custos com combustível e manutenção;
+ Analisar impacto ambiental
+ Analisar partidas de motores
+ Com investimento
** Utilização de Controlador de Demanda
+ Analisar custos de investimento
+ Definir prioridade de cargas a serem controladas
+ Analisar sistema de automação (supervisório)
** Substituição de equipamentos convencionais por eficientes
+ Luminárias/lâmpadas;
+ Motores;
+ Condicionadores de ar.
+ Qualquer substituição tem investimento

* Eficiência Energética - Iluminação
+ Eficiência luminosa: Relaçã oentre o fluxo luminoso emitido por uma fonte luminosa e sua potência em watts
+ \[E.L = \frac{\Phi}{P}\] (lm/W) (IRC)
+ Medidas de eficiência energética em iluminação: Substituição de lâmpadas, luminárias e reatores
+ Alteração de características do ambiente: cores, alturas, uso de iluminação natural
+ Substituição de lâmpadas tubulares em uma mesma luminária, considerar:
+ Comprimento; diâmetro; eficiência luminosa; tipo; IRC; vida útil

* Substituição de lâmpadas em uma mesma luminária
+ Comparar:
  - Eficiência luminosa;
  - Fluxo luminoso;
  - Potência;
  - IRC;
  - Temperatura de cor;
  - Acessórios;
  - Comprimento;
  - Diâmetro.

* Atividade: Considerando a sala de aula: (até 3 crianças, entrega: 26/09 email)
+ 8 luminárias com 2 lâmpadas fluorescentes tubulares de 32W, com 1 reator duplo em cada luminária.
+ Fluxo de cada lâmpada: 2100 lúmens
+ Potência do reator: 10W
+ Comprimento de cada lâmpada: 1,2-1,3m (aprox)
+ Pesquisar e propor a substituição das lâmpadas (5 opções)
+ Sem reduizr os níveis de iluminamento e os IRCs, além das potências

* Resolução
+ Potência por luminária: 2x32 + 10 = 74W

* Eficiência Energética em motores de indução trifásicos
-> Motores convencionais -> motores de alto rendimento;
 - Princípio de funcionamento igual;
 - Materiais e componentes projetados para reduzir as perdas;
+ Perdas podem ser calor, magnética, mecânica
\[\eta (\%) = \frac{Po}{Pi}\times 100 \%\]
\[Pi = Po + \Sigma perdas\]
\[C = P \times \Delta t\]
+ Ex: Um motor 100cv com rendimento de 85\% é substituído por outro comrendimento de 95\%. Considerando que ele funciona 120 horas por mês, qual foi a economia (em kWh) obtida?
\[Pi = \frac{Po}{\eta} = \frac{100 \times 736}{0,85} = 86,59kW\]
\[C = 10390,8 kWh\]
\[Pi = \frac{Po}{\eta} = \frac{100 \times 736}{0,95} = 77,47kW\]
\[C = 9296,4 kWh\]
\[Economia = 1094,4 kWh\]

* Aplicação de Inversor ou Conversor de Frequência
\[\eta_{s} = \frac{120f}{p}\]

* Trabalho Qualidade e Eficiência energética
1.
   a (F)
   b (F)
   c (F)
   d (F)
2.
   d

3. E = 500 lux; A = 10x8m^2; Pé direito: 4,0m; Plano de trabalho está a 0,7m do chão; Paredes e teto claros, piso é escuro; Fluxo de cada lâmpada: 2400lm; Fdl = 0,75

\[Hlp = 4,0 - 0,7 = 3,3 m\]

\[k = \frac{10\times 8}{3,3(10+8)} = 1,347\]

+ Teto = 50\%
+ Parede = 50\%
+ Piso = 10\%

\[Fu = \frac{1,5-1,25}{1,5-1,347} = \frac{0,48-0,43}{0,48-Fu}\]


\[Fu = \frac{0,25}{0,153} = \frac{0,05}{0,48-Fu}\]

\[Fu = 0,44\]

\[Phi = \frac{E\times S}{Fu\times Fdl} = \frac{500\times 80}{0,44\times 0,75} =  121 212,1212 lux\]

\[\Phi_{LUM} = 2400 lm\]

\[\frac{\Phi_{T}}{\Phi_{LUM}} \approx 51\]

4.

+ Área: 10x8m^2
+ Quantidade de luminárias: 51
+ Hlp: 3,3m
+ 3x + 2x/2 = 10m (x aqui é a distância entre luminária e parede)
+ 2y + 2y/2 = 8m
+ x = 2m < Hlp
+ y = 2m < Hlp

* Distribuição de luminárias
+ \[X < Hlp\]
+ \[Y < Hlp\]
+ X e Y: Distância entre luminárias
+ Hlp: Distância entre luminária e plano de trabalho
** Exemplo
+ Área: 8x6m^2
+ Quantidade de luminárias: 12
+ Hlp: 2,8m
+ 3x + 2x/2 = 8m (x aqui é a distância entre luminária e parede)
+ 2y + 2y/2 = 6m
+ x = 2m < Hlp
+ y = 2m < Hlp

* Faturamento de consumo de energia e demanda reativas
+ Art. 302 (norma 1000 aneel)
+ Fr (fator de potência de referência) = 0,92 (cap/ind)
+ Grupo A;
+ Em MS: 23:30h-05:30h (capacitivo), 05:30h-23:30h (indutivo) -> Todos os dias

\[E_{RE} = \Sigma [EEAM_{T} \times (\frac{fr}{fT} - 1)] \times V_{ERE}\]
+ ERE = Faturamento de Energia ou Consumo de Reativos (R$);
+ EEAMT = Energia Elétrica Ativa Medida em um intervalo de t = 1 horas (kWh ou mWh);
+ ft = Fator de Potência horário;
+ Vere = Valor da tarifa do consumo;
+ \[\Sigma\] é o somatório do mês
+ Norma -> Bandeira verde do subgrupo B1 -> R$/kWh ou R$/MWh
+ Exemplo: Calcule os faturamentos de consumo de energia reativa: (Vere = 1,01 R$/kWh)
  a) 15:30h - 150 kWh - ft = 0,85 (ind)
\[E_{RE} = \Sigma [150 \times (\frac{0,92}{0,85} - 1)] \times 1,01 = 12,48\]
  a) 16:30h - 120 kWh - ft = 0,80 (cap)
Só é cobrado indutivo
  b) 01:30h - 100 kWh - ft = 0,81 (cap)
\[E_{RE} = \Sigma [100 \times (\frac{0,92}{0,81} - 1)] \times 1,01 = 13,72\]
  a) 08:00h - 95 kWh - ft = 0,95 (ind)
Maior que 0,92
