#+TITLE: Estatistica
#+DESCRIPTION: Instalações Elétricas Industriais - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Avaliações
+ Lista de exercícios - 29/08
+ Prova parcial - 12/09
+ Prova bimestral - 26/09

* População ou amostra
** Tamanho da populaçõa
+ Margem de erro é medido de acordo com o objetivo, e pode ir até 5%
+ Casos que a margem de erro é 5% são apenas pesquisas informativas e que não tenham risco de vida
+ Assim, podemos calcular o tamanho de amostra
** Exemplo 1
+ População -> 3200
+ Margem de erro -> 5%
\[Ao = \frac{1}{Eo}^2\]
\[Ao = 400\]
\[Af = \frac{P*Ao}{P+Ao}\]
\[Af = 356\] (arredondado para a maior unidade)
+ A porcentagem da população (tamanho da amostra) que temos que utilizar é dado por uma regra de 3, onde 3200 é 100\%, então 356 (Amostra final) corresponde a 11,125\%
** Exemplo 2
+ População = 120.000, população masculina = 55.000, população feminina = 65.000
+ Eo = 4%
+ Utilizando aleatória simples (utiliza o todo)
\[Ao = \frac{1}{0,04}^2\]
\[Ao = 125\]
\[Af = \frac{120000*625}{120000+625 = 622 pessoas\]
\[X\% = 0,52%\]
+ Utilizando amostragem estratificada
+ Masculino
\[Afm = \frac{P*Ao}{P+Ao} = \frac{55.000*625}{55.000+625} = 618\]
\[X\% = 1,12\% (considerando 55000 pessoas\]
+ Feminino
\[Aff = \frac{P*Ao}{P+Ao} = \frac{65.000*625}{65.000+625} = 620\]
\[X\% = 0,95\% (considerando 65000 pessoas)\]
+ A soma dos grupos nos diz quantas pessoas temos que entrevistar
\[Af = Afm + Aff = 1238\]
\[X\% = 1,03\% (considerando 120000 pessoas)\]

* Variáveis
+ Perguntas objetivas -> Dominío de resposta
+ Se alguém não responder uma pergunta temos um problema com nosso instrumento de coleta de dados
+ Temos variáveis qualitativas e quantitativas
+ Quantitativa pode ser discreta e contínua
+ Qualitativa pode ser nominal (que pode ser exclusivo) e ordinal

* Exercício - Revisão
+ Com uma população de 14363 pessoas Ana decidiu fazer uso de amostragem, para tanto, definiu uma margem de erro de 4\%. Qual o tamanho da amostra?
\[Ao = \frac{1}{Eo}^2\]
\[Ao = 625\]
\[Af = \frac{P*Ao}{P+Ao}\]
\[Af = \frac{14363*625}{14363+625}\]
\[Af = 599\] (arredondado para a maior unidade)
+ A porcentagem da população (tamanho da amostra) que temos que utilizar é dado por uma regra de 3, onde 14363 é 100\%, logo 599 é 4,17\%

* Exercício 2 - Revisão
** Classifique as variáveis listadas a seguir
+ Nº de filhos - Quantitativa discreta
+ Tipo sanguíneo - Qualitativo nominal
+ Escola de dor - Qualitativo ordinal
+ CPF - Qualitativo nominal
+ Massa - Quantitativo contínuo
+ IMC - Quantitativo contínuo
+ Nota - Quantitativo contínuo
+ Salario - Quantitativo contínuo

* Exercício - Revisão
+ Paulo lançou 4 vezes um dado (fair)
+ 1 1 6 5 4 4 3 2 3 4 5 1 6 6 5 5 1 3 2 2 6 1 5 2 2 4 3 2 3
+ Pode aplicar as técnicas estatísticas linearmente, ou agrupados
+ Distribuição de frequência absoluta

| nº | f |
|  1 | 5 |
|  2 | 6 |
|  3 | 5 |
|  4 | 4 |
|  5 | 5 |
|  6 | 4 |

+ Distribuição de Classe
| nº       | f |
| 1 <- 3   |   |
| 4 <- 6   | 5 |
| Acima de |   |

* Exerício 2
+ Considerando a distribuição de frequência absoluta calcular média, moda e frequência relativa

|   nº filhos |  f |
|           0 | 12 |
|           1 | 23 |
|           2 | 49 |
|           3 | 26 |
|           4 |  8 |
| Acima de 4n |  3 |

+ Média: \[X = (0*12)+(1*23) + (2*49) + (3*26) + (4*8) + (5*3)/121\] = 2,03 filhos
+ Moda: 2
+ Frequência relativa:
|   nº filhos | fr                  |
|           0 | 12x100/121= 9.91\%  |
|           1 | 23x100/121= 19.00\% |
|           2 | 49x100/121= 40.49\% |
|           3 | 26x100/121= 21.48\% |
|           4 | 8x100/121= 6.61\%   |
| Acima de 4n | 3x100/121= 2.47\%   |

* Organizando dados - Distribuição de classe
+ Distribuição em classe é só para variáveis quantitativas discretas e contínuas
+ Considerando os dados referente a avaliação parcial segue as notas
  | 7,2 | 8,1  | 9,1 | 2,0 | 6,8 |
  | 4,0 | 6,5  | 9,3 | 8,0 | 9,0 |
  | 6,3 | 7,2, | 8,4 | 6,0 | 5,5 |
  | 8,4 | 4,2  | 3,0 | 2,5 | 6,6 |
  | 9,0 | 9,8  | 2,1 | 6,9 | 4,1 |
+ Maior nota= 9,8
+ Menor nota= 2,0
+ Amplitude amostral= Maior nota - menor nota = 9,8 - 2,0 = 7,8

| Nota    |  f |  \% | fa |
| 2 <- 4  |  4 |  16 |  4 |
| 4 <- 6  |  4 |  16 |  8 |
| 6 <- 8  |  8 |  32 | 16 |
| 8 <- 10 |  9 |  36 | 25 |
| ......  | 25 | 100 |    |
+ Cada intervalo na coluna da nota é uma classe e a diferença entre a maior e menor é a amplitude da classe (h) -> limite superior - limite inferior
+ É normatizado que a tabela tenha abertura nas laterais (diferente do representado aqui) e não tenha divisão entre as linhas
+ \% Relação da parte em relação ao todo expresso em \% \[\frac{4}{25}\cdots 100 =\]

+ O número de classe é um número inteiro próximo de K:
\[K = 1 + 3,3log(n)\]
Considerando n = 600 elementos
\[K = 1 + 3,3log(600)\]
\[K = 1 + 3,3\times 2,7\]
\[K = 1 + 9,14\]
\[K = 10,14\]
+ K é 10 ou 11
** Amplitude da classe para k = 10
\[ampclasse = \frac{AmplitudeAmostral}{K}\]
** Amplitude da classe para k = 11
\[ampclasse = \frac{AmplitudeAmostral}{K}\]

* Organizando altura
| 1,78 | 1,55 | 1,74 | 1,76 | 1,82 | 1,75  |
| 1,60 | 1,71 | 1,63 | 1,80 | 1,70 | 1,77  |
| 1,84 | 1,75 | 1,74 | 1,72 | 1,76 | 1,58  |
| 1,60 | 1,73 | 1,75 | 1,54 | 1,74 | 1,76  |
| 1,70 | 1,74 | 1,76 | 1,70 | 1,74 | c1,66 |
| 1,60 | 1,57 | 1,65 | 1,63 |      |       |

+ k = 5,917 -> 5 ou 6
\[ampclasse = \frac{0,3}{6} = 0,05\]
+ Maior valor = 1,84
+ Menor valor = 1,54
+ Amplitude amostral = 0,3
| Altura        |  f | \%    | fa |
| 1,54 <- 1,59  |  4 | 12,90 |  4 |
| 1,59 <- 1,64  |  5 | 16,13 |  9 |
| 1,64 <- 1,69  |  2 | 6,45  | 11 |
| 1,69 <- 1,74  |  5 | 16,13 | 16 |
| 1,74 <- 1,79  | 12 | 38,70 | 28 |
| 1,79 <-> 1,84 |  3 | 9,68  | 31 |

* Exercício avaliativo
+ Grupo: 03 acadêmicos
+ Passo 1 -> Elaborar um objetivo de pesquisa na área do seu curso técnico e 03 específicos
+ Lembre-se: Deve iniciar com verbo no infinito
+ Passo 2 -> Elaborar um instrumento de coleta de dados, constituida de 15 questões, organizadas em definição de perfil específica no tema
** O exercicio
+ Passo 1: Avaliar o perfil dos acadêmicos formando no curso técnico integrado em eletrotecnica considerado o grau de empregabilidade
+ Traçar as qualidades exigidas pelo mercado de trabalho na aŕea de eletrotécnica e o perfil dos acadêmicos
+ Correlacionar os dados dos acadêmicos com o exigido pelo mercado de trabalho
+ Elaborar uma escala de nível de preparação considerando o perfil avaliado e o quanto eles se considera apto a determinada vaga
+ Passo 2:
  1) Qual o seu sexo? (  ) Feminino (  ) Masculino
  2) Quanto tempo durou sua formação técnica durante o ensino médio? (  ) 2 anos (  ) 2 anos e meio (  ) 3 anos (  ) 3 anos e meio (  ) 4 anos ou mais
  3) Durante seu ensino médio, você realizou trabalho de conclusão de curso (TCC)? (  ) Sim (  ) Não
  4) Em uma escala de 1 a 5, quão importante você acredita que foi ou seria a realização do TCC para o mercado de trabalho?
  5) Durante seu ensino médio, você realizou estágio na área técnica? (  ) Sim (  ) Não
  6) Em uma escala de 1 a 5, quão importante você acredita que foi seu estágio para sua formação técnica?
  7) Em uma escala de 1 a 5, quão importante você acredita que foram as aulas de laboratório para sua formação como técnico?
  8) Em uma escala de 1 a 5, quão importante você acredita que foram as aulas teóricas para sua formação como técnico?
  9) Você acredita ter algum conhecimento que não foi abordado durante sua formação técnica? (  ) Sim (  ) Não
  10) A pandemia afetou seu acesso a informação das aulas de laboratório ou teóricas? (  ) Sim (  ) Não
  11) Qua(is)l disciplina(s) você acredita ter contribuido mais para a sua formação técnica? (O domínio se refere as disciplinas técnicas encontradas na matriz do curso)
  12) Pretende entrar no mercado de trabalho logo após sua formação no ensino médio técnico? (  ) Sim (  ) Não
  13) Pretende ir ao nível superior para se especializar na área? (  ) Sim (  ) Não
  14) Você acredita que a estrutura da sua escola colaborou para sua preparação técnica? (  ) Sim (  ) Não
  15) No geral, você se considera apto a trabalhar na área de eletrotécnica?

* Métricas de posicionamento
+ Mediana (AKA quartil 2)
+ Quartil 1
+ Quartil 3
+ 50% - mediana - 50%
+ 25% -> 1/4 dos posicionamentos -> quartil 1
+ 75% dos posicionamentos -> quartil 3
  + Considere os dados referente a variável idade
| 12 |  8 | 1ºp  |              |                                          |
| 11 |  8 | 2ºp  |              |                                          |
|  8 |  9 | 3ºp  |              | Até aqui 25% entre 3 e 4 (Q1) = 9,5      |
| 14 | 10 | 4ºp  |              |                                          |
| 10 | 11 | 5ºp  |              |                                          |
|  9 | 11 | 6ºp  | Até aqui 50% |                                          |
|  8 | 12 | 7ºp  | Mediana = 12 |                                          |
| 14 | 12 | 8ºp  |              |                                          |
| 12 | 12 | 9ºp  |              |                                          |
| 11 | 13 | 10ºp |              | Até aqui 75% entre o 10 e 11 (Q3) = 13,5 |
| 12 | 14 | 11ºp |              |                                          |
| 13 | 14 | 12ºp |              |                                          |
| 15 | 15 | 13ºp | Até aqui 50% |                                          |

+ Em uma distribuição de classe
\[Q1 = lim_{inf} + [(\frac{\frac{Ef}{4} - faa}{f})]\cdot H\]
\[Q2 = lim_{inf} + [(\frac{\frac{Ef}{2} - faa}{f})]\cdot H\]
\[Q3 = lim_{inf} + [(\frac{\frac{3Ef}{4} - faa}{f})]\cdot H\]

+ Calcular média, mediana, Q1, Q3 e moda da distribuição de classe a seguir
| nota    |  f | Pm         | Pm*f |
| 0 <- 2  | 12 | 2+0/2 = 1  |   12 |
| 2 <- 4  | 21 | 2+4/2 = 3  |   63 |
| 4 <- 6  | 18 | 4+6/2 = 5  |   90 |
| 6 <- 8  | 14 | 6+8/2 = 7  |   98 |
| 8 <- 10 |  7 | 8+10/2 = 9 |   63 |
|         | 72 |            |  326 |

\[X = 326/72 = 4,53 nota\]
+ Mediana -> Ef/2 = 72/2 = 36 (essa é a posição)

\[med = lim_{inf} + [(\frac{\frac{Ef}{2} - faa}{f})]\cdot H\]
\[med = 4 + [(\frac{36 - 33}{18})]\cdot 2\]
\[med = 4,333\]

+ Q1 = Ef/4 = 72/4 = 18
\[Q1 = lim_{inf} + [(\frac{\frac{Ef}{4} - faa}{f})]\cdot H\]

\[Q1 = 2 + [(\frac{18 - 12}{21})]\cdot 2\]
\[Q1 = 2,57\]

+ Q3 = 3Ef/4 = 54
\[Q3 = lim_{inf} + [(\frac{\frac{3Ef}{4} - faa}{f})]\cdot H\]
\[Q3 = 6 + [(\frac{54 - 51}{14})]\cdot 2\]
\[Q3 = 6,42\]

** Moda
 + Passo 1: Localiza a classe que contém a moda (classe de maior frequência): 2 <- 4 21
\[moda = lim_{inf} + [(\frac{fant}{fant+fpost})]\cdot H\]
\[moda = 2 + [(\frac{12}{12+18})]\cdot 2\]
\[moda = 2,8\]
+ Moda < Mediana < Média

* Métricas de dispersão
| Nota    | 1ºb | 2ºb | 3ºb | 4ºb | média |
| Carlos  | 5,0 | 5,0 | 5,0 | 5,0 | 5,0   |
| Fabio   | 2,0 | 8,0 | 2,0 | 8,0 | 5,0   |
| Rui     | 6,0 | 4,0 | 4,0 | 6,0 | 5,0   |
| Wíllian | 10  | 0   | 10  | 0   | 5,0   |
+ Apesar de as médias serem iguais, o comportamento das notas são diferentes
+ Amplitude amostral
+ Variância
+ Desvio padrão
+ Covariância

+ Considere a distribuição de classe a seguir, calcular o desvio padrão
+ Desvio médio: o quanto cada classe se afasta da média
+ Desvio médio quadrado: considero o tamanho da amostra
  | Nota    |  f | P.M | P.M. * f | Desvio médio     | (Desvio médio)^2   |
  | 0 <- 2  |  4 |   1 |        4 | 1 - 5,08 = -4,08 | (-4,08)^2 = 16,64  |
  | 2 <- 4  | 12 |   3 |       36 | 3 - 5,08 = -2,08 | (-2,08)^2 = 4,32   |
  | 4 <- 6  | 16 |   5 |       80 | 5 - 5,08 = -0,08 | (-0,08)^2 = 0,0064 |
  | 6 <- 8  |  8 |   7 |       56 | 7 - 5,08 =  1,92 | (1,92)^2 = 3,68    |
  | 8 <- 10 |  7 |   9 |       63 | 9 - 5,08 =  3,92 | (3,92)^2 = 15,36   |
  | Total   | 47 |     |      239 |                  | 34,88              |
+ X = 239/47 = 5,08
\[\sigma = \sqrt{\frac{\Sigma (desviomedio)^2}{n}} = \sqrt{\frac{40,0064}{47}} = \sqrt{0,8512} = 0,922\]
+ Média mais desvio padrão = 6,002
+ Média = 5,08
+ Média menos desvio padrão = 4,158
+ Entre 6,002 e 4,158 encontra-se a maioria dos alunos, quem está em cima e em baixo está fora do padrão
+ Para que eu possa comparar essa média com a média de outra turma, eu uso a covariância
+ \[Cov = \frac{\sigma}{X} * 100 = \frac{0,922}{5,08}*100 = 18,14\%\]

* Exercícios
1) Considerando uma média de X = 36,4 unidades e um desvio padrão de 0,46 unidades^2 determinar a covariância

+ \[Cov = \frac{\sigma}{X} * 100 = \frac{0,46}{36,4}*100 = 1,26\%\]

2) Qual a diferença de uma amostragem aleatoria simples e uma estratificada
+ Amostragem aleatória não existe nenhuma variável que interfere na opnião dos entrevistado, apresentando comportamento universal entre seus componentes, já a amostragem determinada variável obriga a dividir o grupo em subgrupos
3) O que é uma amostragem de conglomerado?
+ Estrutura organizacional pronta considerando o olhar do entrevistador
4) Cita três métricas de tendência central de posicionamento
+ Mediana, quartil 1 e quartil 3
5) O que vem a ser o processo de inferência estatistica?
+ É a transposição dos resultados da amostragem a população a ela vinculada -> não é obrigatório, só precisa se usar a amostragem
6) Considere a questões abaixo
   A sua idade está vinculada a qual faixa estária?
   ( ) De 14 a 16 anos
   ( ) De 17 a 19 anos
   ( ) De 20 a 22 anos
   ( ) Acima de 22 anoas
   Classficar a variável
   - Qualitativa nominal
   Qual a sua idade?
   Classificar a variável
   - Qualitativa discreta

| IMC     |  f | fa |
| 16 <-18 |  2 |  2 |
| 18 <-20 | 16 | 18 |
| 20 <-22 | 22 | 40 |
| 22 <-24 | 14 | 54 |
| 24 <-26 | 10 | 64 |
|         |    |    |
+ Calcular as métricas de posicionamento
+ Passo 1 -> Definir a posição
+ Passo 2 -> Localizar classe
+ Passo 3 -> Calcular:
*  Mediana
  + P1 -> 64/2 = 32
  + P2 -> 20 <-22 f= 22
  + P3 ->

\[med = lim_{inf} + [(\frac{\frac{\Sigma f}{2} - faa}{f})]\cdot H\]
\[med = 20 + [(\frac{32 - 18}{22})]\cdot 2\] = 21,27
* Quartil 1
+ P1 -> 64/4 = 16
+ P2 -> 18 <-20 f= 16
\[Q1 = lim_{inf} + [(\frac{\frac{\Sigma f}{4} - faa}{f})]\cdot H\]
\[Q1 = 18 + [(\frac{\frac{16 - 2}{16})]\cdot 2\] =  19,75

* Quartil 3
+ P1 -> 64*3/4 = 48
+ P2 -> 22 <-24 = 14

\[Q1 = lim_{inf} + [(\frac{\frac{\Sigma f \cdot 3}{4} - faa}{f})]\cdot H\]
\[Q1 = 22 + [(\frac{\frac{48 - 40}{14})]\cdot 2\] = 23,14
