#+TITLE: Geração, Transmissão e Distribuição de Energia Elétrica
#+DESCRIPTION: Geração, Transmissão e Distribuição de Energia Elétrica - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Sistema de Avaliação
+ P1 -> 10,0 (22/8)
+ P2 -> 10,0
\[N1 = \frac{P1+P2+TS}{2}\]
+ P3 -> 10,0
+ P4 -> 10,0
\[N2 = \frac{P3+P4+TS}{2}\]
+ Rec 1 - Substituirá N1
+ Rec 2 - Susbtituirá N2

* Conceitos
+ Equipamento <- Unidade consumidora <- Rede de distribuição urbana ou rural <- Linha de transmissão <- Geração

* Dimensionamento de Entrada de Energia em MT
+ Norma de Distribuição (Energisa) -> NDU 002
+ Para carga instalada maior que 75kW ou para casos especiais
+ Carga instalada é a soma de todas as potências dos equipamentos de uma unidade consumidora em condições de entrar em funcionamento (em kW).

* Exemplo: Calcule a carga instalada (kW) para a relação de equipamentos:
- 2 chuveiros de 5kW -> 10kW
- TUG - Pot. Total: 3000VA - FP = 0,9 -> 2,7kW
- Motor de indução - 3cv - rendimento de 85\% -> 2,6kW
+ Carga instalada: CI = 15,3kW

* Fornecimento de Energia em Tensão Primária
+ Norma de Distribuição unificada (NDU02)
** Rede de Distribuição Urbana (Campo Grande)
+ Tensão Secundária (220/127V);
+ Tensão Primária (13800V).
+ Unidades consumidoras com C.I maior que 75kW necessitam de fornecimento em tensão primária (regra geral).
** Demanda
+ É a média das potências elétricas, ativas ou reativas, solicitadas ao sistema elétrico, durante um intervalo de tempo.
** Fator de demanda
+ Razão entre a demanda máxima e a carga instalada em um intervalo de tempo

* Procedimentos para determinação da potência de trasnformação necessária para uma unidade consumidora (NDU02)
1) Cálculo da carga instalada (kW);
2) De acordo com o ramo de atividade, determinar o fator de demanda (FD) => NDU 02;
3) Aplicar o FD na carga instalada para achar a demanda da unidade consumidora: \[D(kW) = FD\times CI\]
4) Potência de transformação \[=S(kVA) = D/FP = D/0,92\]


* Exercício:
+ Uma fábrica de tijolos possui carga instalada igual a 200kW. Dimensione a potência de transformação necessária para atender a unidade consumidora

* Exercício:
+ Dimensione os componentes para entrada de energia que atenderá a potência de transformação do exemplo anterior (tabela 2 - pag 82):
a) Potência do transformador (kVA) - único:
\[D(kVA) = 200\times 0,91/0,92 = 197,8kVA\]
+ Usaremos de 225 kVA, pois é a potência mais próxima maior
b) Tipo de medição (direta ou indireta; relação de transformação do TC, se necessário);
+ Indireta, com TC-400:5
c) Seção dos condutores do lado secundário (em XLPE/EPR e PVC):
+ EPR/XLPE: 2x{3 de 185 (95)}. PVC = 2x{3 de 300 (150)}
d) Disjuntor termomagnético em BT:

* Exercício (lista):
+ Uma unidade consumidora de energia elétrica que atua no ramo de supermercados deseja que sua entrada de energia seja dimensionada. Ela possui a seguinte relação de equipamentos (cargas):

+ 10 motores de indução trifásicos de 5 cv, com rendimento de 87%;
+ 2 motores de indução trifásicos de 10 cv, com rendimento de 88%;
+ 6 motores de indução monofásicos de ¼ cv, com rendimento de 85%;
+ Potência total em iluminação igual a 30 kVA, com fator de potência de 0,90;
+ Potência total em tomadas de uso geral (TUG) igual a 20 kVA, com fator de potência de 0,88;
+ 6 chuveiros elétricos de 5 kW;
+ 4 condicionadores de ar, tipo split, de 2,5 kVA cada, com fator de potência de 0,86.

a) Calcule a carga instalada da unidade consumidora (kW);
 - 1 cv = 735,498W
 - 1/4 cv = 183,874W, com 85% -> 216,32W -> 6 de cada = 1,297 kW
 - 5 cv = 3677,49W, com 87% -> 845,40 W -> 10 de cada = 42,270 kW
 - 10 cv = 7354,98W, com 88% -> 8357,93W -> 2 de cada = 16,715 kW
 - 30 kVA, com 0,9 de F.P = 27kW
 - 20 kVA, com 0,88 de F.P = 17,6 kW
 - 6 chuveiros elétricos = 30 kW
 - 2,5 kVA, com 0,86 vezes 4 = 8,6 kW
 - Carga instalada (soma de todos os resultados anteriores) = 143,482 kW

b) Calcule a potência, em kVA, necessária para o(s) transformador(es) da entrada de serviço. Considere o fator de potência igual a 0,92 como referência;
 - Multiplicando 143,482 kW por 0,98
 - Dividindo 140,61 por 0,92 =  152,84 kVA

c) Consulte a Norma de Distribuição Unificada nº 2, da concessionária de energia local (Energisa) para verificar qual ou quais potência(s) do(s) transformadores atenderia(m) à unidade consumidora. Tensão secundária: 220/127V;
 - Transformador de 225 kVA (mais próximo de 152,84)

d) A medição será em baixa tensão ou média tensão? Por quê?
 - Baixa tensão, pois utilizou um transformador menor que 300kVA

e) De acordo com a norma, dimensione os condutores do lado secundário do(s) transformador(es). Apresente as especificações tanto para a isolação em PVC quanto em EPR/XLPE. Indique qual seria a seção dos condutores fase e neutro, além de quantos condutores por função poderiam ser utilizados.
 - EPR/XLPE: 2x{3#185(95). PVC = 2x{3#300(150)
   - EPR/XLPE - FASES: 2 condutores por fase de 185 mm^2 (cada), totalizando 6 condutores fase. NEUTRO: 2 condutores por neutro de 95mm^2 (cada), totalizando 2 condutores por neutro
   - PVC - FASES: 2 condutores por fase de 300 mm^2 (cada), totalizando 6 condutores fase. NEUTRO: 2 condutores por neutro de 150mm^2 (cada), totalizando 2 condutores por neutro


f) Qual(is) seria(m) o(s) valor(es) nominal(ais) do(s) disjuntor(es) geral(is) em baixa tensão? Caso seja necessário mais de um transformador, indique para cada um qual seria seu valor.
 - 600A, com CC de 10KA

* Outro exercício
+ Uma unidade consumidora de energia elétrica que atua no ramo de indústria têxtil deseja que sua entrada de energia seja dimensionada. Ela possui a seguinte relação de equipamentos (cargas):

+ 20 motores de indução trifásicos de 3 cv, com rendimento de 83%;
+ 15 motores de indução monofásicos de 1/4 cv, com rendimento de 85%;
+ Potência total em iluminação igual a 50 kVA, com fator de potência de 0,90;
+ Potência total em tomadas de uso geral (TUG) igual a 20 kVA, com fator de potência 0,88;
+ 8 condicionadores de ar, tipo split, de 3,5 kVA cada, com fator de potência de 0,86;

a) Calcule a carga instalada da unidade consumidora (kW);
  - 1 cv = 736W
  - 3 cv = W, com 83% ->  W -> 20 de cada = 53,204kW
  - 1/4 cv = 184W, com 85% -> 216,32W -> 15 de cada = 3,247kW
  - 50 kVA, com 0,9 de F.P = 45kW
  - 3,5 kVA, com 0,86 vezes 8 =  24,08kW
  - Carga instalada (soma de todos os resultados anteriores) = 125,531 kW

b) Calcule a potência, em kVA, necessária para o(s) transformador(es) da entrada de serviço. Considere o fator de potência igual a 0,92 como referência;
  - Usando a demanda típica: 52%
  - Multiplicando 125,531 kW por 0,52
  - Dividindo 65,276 por 0,92 =  70,95 kVA

c) Consulte a Norma de Distribuição Unificada nº 2, da concessionária de energia local (Energisa) para verificar qual ou quais potência(s) do(s) transformadores atenderia(m) à unidade consumidora. Tensão secundária: 220/127V;
  - Transformador de 75 kVA (mais próximo de 70,95)

d) A medição será em baixa tensão ou média tensão? Por quê?
  - Baixa tensão, pois utilizou um transformador menor que 300kVA

e) De acordo com a norma, dimensione os condutores do lado secundário do(s) transformador(es). Apresente as especificações tanto para a isolação em PVC quanto em EPR/XLPE. Indique qual seria a seção dos condutores fase e neutro, além de quantos condutores por função poderiam ser utilizados.
  - EPR/XLPE: 3#95(50). PVC = -
   - EPR/XLPE - FASES: 3 condutores fase de 95 mm^2. NEUTRO: 1 condutores neutro de 50mm^2

f) Qual(is) seria(m) o(s) valor(es) nominal(ais) do(s) disjuntor(es) geral(is) em baixa tensão? Caso seja necessário mais de um transformador, indique para cada um qual seria seu valor.
  - Corrente nominal = 200A, com CC de 10KA

* Treino pra prova
+ Sempre que tiver mais que um transformador e/ou o transformador consumir mais que 300kVA é média tensão?

* Diagramas unifilares
+ MT -> 13,8kV. Três pontos aterrados -> para raios, secundário do transformador e massa (parte metalicas)
+ Medição direta em BT
+ foto
+ Chave seccionadora
+ Condutores fase em MT
+ Para raios
+ Transformador
+ Condutores fase e neutro em BT
+ Medição direta
+ Disjuntor tripolar
+ Malha de aterramento

* Trabalho
+ Até 3 componentes
+ Projeto de entrada de energia em MT
+ Composição: Memorial descrito
+ Desenhos e detalhes de acordo com a norma; NDU 2 (Energia)
+ Diagrama com indicação de dimensionamento
+ Relação de materiais
** Potências
+ 112,5 kVA
+ Pode fazer em mureta
+ Prazo: 28/9 -> pdf por email, arquivo único

* Sistema Interligado Nacional (SIN)
+ Possui o mapa dinâmico de transmissão e usinas
+ ons.org.br

* Redes de Distribuição (NDU 06)
+ Rede primaria (13,8 kV) 3 fases
+ Rede secundária (220/127V) 3 fases + 1 N
+ Componentes: condutores, postes, transformadores, isoladores, acessórios...
+ Dimensionadas de acordo com as cargas instaladas e demandas das unidades consumidoras
+ Outros serviços: telefonia, internet, TV a cabo
** Tipos de projetos de redes: (pg. 18 - NDU 06)
+ Expansão;
+ Reforma; "Substituição"
+ Reforço. "Aumento".

* Atividade do dia 12/09
1. Estrutura N1/T1 possui 1 cruzeta, 3 isoladores, está posicionada em tangêcia ou em alguns casos em ângulos, sendo que neste último a instalação dos condutores nos isoladores deverá ser feita na lateral. A cruzeta das estruturas N1/T1 deve ser instalada do lado oposto ao sentido de tracionamento dos condutores. A estrutura N2/T2 possui 2 cruzetas e 6 isoladores, posicionada em ângulo pouco acentuados ou em tangências. Foi vetada sua utilização em derivação e fim de rede. A estrutura N3/T3 possui 2 cruzetas, 3 isoladores e é utilizada em derivações e fim de rede. A estrutura N4/T4 tem 2 cruzetas, 7 isoladores e é utilizada em ângulos muito acentuados, em mudança de bitolas de condutores e em tangentes.
2. a) Parte de uma rede primaria numa determinada área de uma localidade que alimenta, diretamente ou por intermédio de seus ramais, transformadores de distribuição da concessionária e/ou de consumidores. b) Ligação feita em qualquer ponto de uma rede de distribuição para um alimentador, ramal de alimentador, transformador de distribuição ou ponto de entrega. c) Parta de um alimentador de distribuição que transporta a parcela principal de carga total. Normalmente é constituído por condutor de bitola mais elevada, caracterizao por um dos seguintes fatores: Transporte do total ou de parcela ponderável da carga servida pelo alimentador. Alimentação ao principal consumidor do alimentador. Interligação com outro alimentador, permitindo transferência de carga entre os alimentadores. d) Parte de um alimentador de distribuição que deriva diretamente do tronco do alimentador e) Rede de distribuição situada dentro do perímetro urbano de cidades, vilas, assentamentos e povoados
3. Tensão primaria (13,8/7,96 kV), tensão secundária (220/127V). Pode variar 5% acima e 7% abaixo.
4. Os condutores da rede primária serão de alumínio: 50mm^2, 120mm^2, 185mm^2 para seção nominal, com diâmetros externos aproximados em 14,7, 19,4, 22,6 mm. Os condutores da rede secundária serão condutores de alumínio multiplexados, com condutores fase em alumínio isolados em polietleno (XLPE) para 0,6/1kV e condutor mensageiro (neutro) nu em liga de alumínio. Esses circuitos trifásicos são compostos por 4 fios em qualquer um das configurações: 3x1x35 + 35mm^2, 3x1x70 + 70 mm^2, 3x1x120 + 70mm^2
5. O estai é o termo usado para designar cada um dos cabos utilizados na fixação do poste.

* Atividade
Curso Técnico de Nível Médio Integrado em Eletrotécnica. Geração, Transmissão e Distribuição de Energia Elétrica


EXERCÍCIOS


PARA A REALIZAÇÃO DA ATIVIDADE ACESSE O SITE: http://www.ons.org.br/paginas/sobre-o-sin/mapas


1) De acordo com o Mapa Dinâmico do Sistema Interligado Nacional (SIN), quantas linhas de transmissão atendem a cidade de Corumbá/MS? Qual é sua identificação (nome)? Qual é a sua tensão nominal?
   - Uma linha de transmissão. Linha LT 230kV Anastacio/Corumba 2 C 2 MS. 230kV


2) De acordo com o Mapa Dinâmico do Sistema Interligado Nacional (SIN), cite 2 linhas de transmissão que atendem a cidade de Campo Grande/MS? Quais são suas identificações (nomes)? Quais são suas tensões nominais?
   - Linha LT 138kV CG M. Couto/C.G. Imbirussu 1 MS -> 138kV

   - Linha LT 230kV Chapadao /Imbirussu C 1 MS -> 230kV

3) De acordo com o Mapa Dinâmico do Sistema Interligado Nacional (SIN), cite os nomes de 4 subestações que atendem Campo Grande/MS, além de suas capacidades.
   - Subestação CG Almoxarif. 0MW

   - Subestação C.G. Lageado. 25MW

   - Usina William Arjona. 206MW

   - Subestação IMBIRUSSU. 550MW

4) De acordo com o Mapa Dinâmico do Sistema Interligado Nacional (SIN), cite os nomes de 6 usinas eólicas localizadas no nordeste brasileiro, além de suas capacidades de geração.
   - Usina Rio do Fogo. 49MW

   - Usina Riachão I. 30MW

   - Usina Riachão II. 27MW

   - Usina Riachão IV. 30MW

   - Usina Riachão VI. 30MW

   - Usina União dos Ventos 01. 22MW

5) De acordo com o Mapa Dinâmico do Sistema Interligado Nacional (SIN), cite o nome de 1 usina nuclear situada no Brasil? Em que cidade/estado está localizada? Qual sua capacidade de geração? Quantas linhas de transmissão partem dela e quais suas tensões nominais?
   - Usina ALM. ÁLVARO ALBERTO I. Angra dos Reis/RJ. 1990MW. 1 linha de transmissão -> Linha LT 500kV ANGRA/ANGRA FUR C 2 RJ, com tensão nominal de 500kV

* Atividade 26/09
Grupo de até 3 estudantes.
Prazo: 26/9/2022 - 23:59h.

Pesquise:

1) Quais as vantagens das usinas hidrelétricas em relação às outras fontes de energia no Brasil? Cite 4

- fonte limpa e renovável
- custo de produção de energia baixo
- não produz gases do efeito estufa
- custo baixo de produção de energia

2) Quais as desvantagens das usinas hidrelétricas em relação às outras fontes de energia no Brasil? Cite 4.
- alteração do curso e do nível natural dos rios
- diminuição da geração nos períodos de seca
- realocação das populações ribeirinhas e nativas
- influência na flora e a fauna das áreas alagadas

3) O que significa SIN em se tratando de Geração, Transmissão e Geração de Energia Elétrica? Qual é sua finalidade? Por quantos subsistemas ele é constituído?

O Sistema Interligado Nacional é composto pelo sistema elétrico do país a qual é conectado quase todas as unidades de geração com as unidades de transmissão e as unidades de transmissão conectadas com as unidades de distribuição. É constituído por 4 subsistemas: Sul, Sudeste/Centro-Oeste, Nordeste e a maior parte do Norte.

4) O que significa ONS em se tratando de Geração, Transmissão e Geração de Energia Elétrica? Qual é sua finalidade?
O ONS (Operador Nacional do Sistema Elétrico) e é o orgão que coordenada e controla a operação das instalações de geração e transmissão de energia elétrica no Sistema Interligado Nacional. Sua finalidade é gerenciar as diferentes fontes de energia e a rede de transmissão, mantendo assim a segurança do suprimento elétrico em todo o país.

5) O que significa ANEEL em se tratando de Geração, Transmissão e Geração de Energia Elétrica? Qual é sua finalidade?
ANEEL é a Agência Nacional de Energia Elétrica e é a agência reguladora do setor elétrico brasileiro, com a finalidade de regular e fiscalizar a geração, transmissão e distribuição de energia elétrica, como também a sua comercialização

6) Qual é o segundo tipo de usina geradora mais presente no território nacional? Qual é sua capacidade de geração total?
Eólica, 22,214GW

7) Qual é o terceiro tipo de usina geradora mais presente no território nacional? Qual é sua capacidade de geração total?
Biomassa, 14,989GW

8) Quais são as 2 principais classes de tensão de linhas de transmissão existentes em território nacional?
- A1 (Tensão de fornecimento igual ou superior a 230kV) e A2 (Tensão de fornecimento entre 88kV e 138kV)

9) O que são sistemas isolados em se tratando de SIN? Cite 2 regiões/locais onde estão presentes.
- Sistemas de energia elétrica que a carga não está conectada à geração e não é necessário sua conexão à malha interligada de transmissão. Boa Vista (Roraima) e Fernando de Noronha

10) Qual é a finalidade das subestações em se tratando de interligação entre os sistema de transmissão e as redes de distribuição? Descreva suas principais partes.
- Esse tipo de subestação não faz alteração de tensão e apenas isola sistemas, interliga circuitos e faz a interligação entre subestações de distribuição e centrais de transmissão. Chaves seccionadora  que além de desempenhar a função de interruptor, é capaz de, na posição aberta, garantir a distância de isolamento , de acordo o nível de tensão do circuito. Para-raios que são utilizados para proteger os equipamentos de uma subestação das descargas atmosféricas que podem provocar sobretensões elevadas no sistema (sobretensões de origem externa). Transformador de Instrumentos (TC's e TP's) são equipamentos que garantem o funcionamento dos dispositivos de proteção e segurança funcionamento adequado, sem que para isso estejam ligados em grandes valores de correntes ou tensão.
LEMBRETE: A entrega do projeto de entrada de energia elétrica foi adiado para o dia 3/10/2022.

Composição da P2: Projeto (5,0) + Atividade SIN (2,0) + Atividade 3 (3,0) + Atividade estruturas/definições (1,0) = 11,0 pontos.

* Rede de Distribuição Urbana
+ Componentes do levantamento de campo da aula passada
+ O 4º condutor na entrada de energia subterrânea do câmpus Campo Grande?
+ Componentes do levantamento de campo da aula passada:
  + Banco de Capacitores trifásicos em média tensão: melhorar níveis de tensão e corrigir o FP
  + Chave faca (Média Tensão): Utilizada para seccionamento (manobra) -> Três unidades
  + Chave fusível (Média Tensão): Proteção contra correntes e curto-circuito e manobra
  + Outros: Rede de Distribuição em BT em MT
  + MT: 3 condutores (Fases) - 13,8 kV
  + BT: 4 condutores (3 Fases + Neutro) - 220/127V
  + Estruturas N1, N3, N4
  + Isoladores, cruzetas, postes de concreto

* Linhas de transmissão/redes de distribuição
+ Torres -> Linhas
+ Postes -> Distribuição aérea
+ Postes -> concreto
-> Distribuição subterrânea
