#+TITLE: Instalações Elétricas Industriais
#+DESCRIPTION: Instalações Elétricas Industriais - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Avaliações
+ P1.1 - 5.0 pt - 16/03 - REC1 - 10.0 pt - 22/6
+ P1.2 - 5.0 pt - 6/4
+ P2.1 - 5.0 pt - 4/5 - REC2 - 10.0 pt - 29/6
+ P2.2 - 5.0 pt - 8/6

* Revisão
** Potências
#+ATTR_HTML: alt: waterwave :title Triângulo de Potências :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://luispengler.github.io/virtual-notebook/12th-grade/doc/industriais/triangulopot.jpg
+ P: Potência Ativa (W -> Luz, calor, som, movimento)
+ QL: Potência Reativa Indutiva (VarL) (Campo Magnético). Não dá pra ver nessa imagem, mas essa pot. acontece no eixo reativo no sentido para cima
+ QC: Potência Reativa Capacitiva (VarC) (Carga/Descarga de capacitores). Não dá pra ver nessa imagem, mas essa pot. acontece no eixo reativo no sentido para baixo
+ S: Potência Aparente (VA). Essa é a potência mais importante, pois usaremos para dimensionamento
\[S=\sqrt{P^2+Q^2}\]
\[I=\frac{S}{V}\]

** Fator de Potência
*** Para QL > QC
+ \[QL'=QL-QC\]
+ Fator de Potência indutivo
\[cos\phi=\frac{P}{S}\]
*** Para QC > QL
+ \[QC'=QC-QL'\]
+ Fator de Potência capacitivo
\[cos\phi=\frac{P}{S}\]
*** Para QL > QC
+ \[QC=QL=0\]
+ Fator de Potência unitário
\[cos\phi=\frac{P}{S}=\frac{P}{P}=1\]

* Conteúdo até agora (08/03)
** Partes Básicas
+ Estator (fixa): Ligada à rede de energia elétrica
+ Rotor (móvel): Ligada à carga a ser movimentada

** Potência Nominal
+ Potência Mecânica de saída ao ser aplicada uma tensão nominal, com frequência nominal e corrente nominal
+ Potência de entrada (elétrica)
+ Perdas: Calor, magnetimo, mecânicas (W)

** Rendimento
+ Relação entre a potência de saída e a entrada

\[\eta(%)=\frac{Po}{Pt}\cdot 100%\]

\[Pi=Po+\Sigma perdas\]

1. Exemplo 1: Um motor de 4cv possui rendimento de 85%. Calcule:
   a) Potência de saída (W)
      \[Po=4cv=2944W\]
   b) Potência de entrada (W)
      \[\eta(%)=85%=\frac{2944}{Pi}\cdot 100%\]
      \[Pi=2944\cdot \frac{100}{85}=3463,52W\]
   c) Perdas associadas (W)
      \[Perdas=3463,52-2944=519,53W\]

+ Potência Reativa \[VA_{rL}\] -> Responsável pela criação do magnetismo
+ Potência Aparente \[VA\] -> Soma vetorial das potências ativa e reativa
+ Fator de potência -> Relação entre as potências ativa e aparente
  \[F.P. = \frac{P}{S}=cos\theta\]

** Dados nominais de \[MI3\phi\]
*** Fator de Potência
+ \[F.P.=cos\phi=\frac{P}{S}\]
*** Corrente nominal
\[Inm=\frac{Pnm}{\sqrt{3}\cdot cos\phi\cdot \eta\cdot VFF\]

+ Pnm é a mesma que PO, ou potência de output, que é a potência mecânica

1. Exemplo: Dado um motor de indução trifásico 220V; 4cv; F.P.=0,85; \[\eta=82\%\]. Calcule suas potências de entrada e sua corrente nominal.
   \[PO=4\cdot 736=2944W\]
   \[Inm=\frac{2944}{\sqrt{3}\cdot 0,85\cdot 0,82\cdot 220} = \frac{2944}{265,59} = 11,08A\]
   \[Si=\frac{Pi}{F.P.}=4378,34 VA\]
   \[Vi=\sqrt{S^2-P^2}=2506VarL\]

*** Corrente para um circuito trifásico
\[I3\phi=\frac{SI}{\sqrt{3}\cdot VFF}=\frac{PO}{VFF\cdot \eta\cdot cos\phi\cdot \sqrt{3}}\]
+ VFF = Tensão entre qualquer par de fases
\[F.P.=cos\phi=\frac{Pi}{Si}\]
\[Si=\frac{Pi}{cos\phi}\]
\[Si=\frac{Po}{\eta\cdot cos\phi}\]

*** Questões
1. Um motor de 10cv possui rendimento igual a 85% e fator de potência de 0,82. Ele é de indução trifásico e possui tensão nominal de 220V. Calcule/apresente:
   a) Potência de saída (W);
      \[10\cdot 736=7360W\]
   b) Potência de entrada (W);
      \[7360\cdot \frac{100}{85} = 8658,82W\]
   c) Perdas (W);
      \[8658,82-7360=1298,82W\]
   d) Potência aparente (VA);
      \[\frac{P}{S}=0,82=\frac{P}{0,82}=S=10559,53VA\]
   e) Potência reativa (VarL);
      \[10559,53=\sqrt{8658,82^2+Q^2}\]
      \[10559,53^2=74975163,79+Q^2\]
      \[111503673,8-74975163,79=Q^2\]
      \[36528510,03=Q^2\]
      \[Q=6043,882 VAR\]
   f) Corrente nominal (A)
      \[Inm=\frac{7360}{\sqrt{3}\cdot 0,82\cdot 0,85\cdot 220}=\frac{7360}{265,5926}=27,71A\]

2. Um motor de indução trifásico possui corrente nominal de 15A. Sua tensão nominal é 220; F.P.=0,85;\[\eta=88%\]. Calcule suas perdas
   \[Po=15\cdot \sqrt{3}\cdot 220\cdot 0,85\cdot 0,88\]
   \[Po=4275,39W\]
   \[Pi=4275\cdot \frac{100}{88}=4857,9545W\]
   \[Perdas=4857,95-4275,39=582,56W\]

** Velocidade Síncrona
+ f: Frequência da tensão da rede (Hz)
+ p: Número de polos do motor
\[ns=\frac{120.f}{p}\]
+ É a velocidade do campo eletromagnético girante produzido pelo estator
** Escorregamento
+ É a diferença entre a velocidade síncrona e a velocidade no eixo do motor (unidade em rpm)
  \[s=n_s-n\]
\[s(\%)=\frac{(n_s-n)}{n_s}\cdot 100\%\
\[s=\frac{n_s-n}{n}\]

* Dados Nominais de motores de indução - continuação (23/03)
** Corrente de Partida \[Ip\]
+ Necessária para iniciar o movimento do eixo do motor
+ Em alguns casos é apresentada a relação \[\frac{Ip}{In}\], onde \[In\] é a corrente nominal do motor.
+ Ex: A corrente de partida é 5 vezes maior que a nominal
  \[\frac{Ip}{In}=5\]
+ A corrente de partida é utilizada para os dimensionamentos de dispositivos de acionamentos e proteções de motores
+ A corrente de partida pode durar

** Grau de proteção (IP)
+ Proteção de equipamentos elétricos (seus invólucros) contra a entrada de materiais sólidos e umidade.
+ São utilizados 2 algarismos: o primeiro representa a proteção contra objetos sólidos e o segundo contra água.

** Fator de Serviço (FS)
+ É um número que pode ser multiplicado pela potência nominal do motor, a fim de se obter a carga permissível que o mesmo pode acionar, em regime contínuo, dentro de condições estabelecidos pela norma.

** Exercícios
1. Um motor de indução trifásico, 220V, F.P. = 0.85; 10 cv; \[\eta=84\%\]; 4 polos; 60Hz, possui F.S. = 1,15 e \[\frac{Ip}{In}=10\]. Calcule:
   a) Velocidade síncrona;
      \[ns=\frac{120\cdot 60}{4} = 1800 RPM\]
   b) Velocidade nominal para escorregamento de 3%;
      \[100\% - 3\% = 97\%\cdot ns = 1746\]
   c) Corrente de partida;
      \[Po=10\cdot 736 = 7360W\]
      \[Inm=\frac{7360}{0,85\cdot 0,84\cdot 220\cdot \sqrt{3}} = 27,05A\]
      \[frac{Ip}{In}=10 = 270,5A\]
   d) Potência de saída máxima permitida.
      \[Po_{max}=10\cdot 736\cdot 1,15 = 8464W\]
   e) Potência de entrada máxima quando a potência de saída máxima é utilizada
      \[\frac{Po_{max}}{0,84}= 10076,19W\]

* Cálculo Luminotécnico
** Fluxo luminoso
+ Radiação luminosa emitida por uma fonte
+ Unidade: Lúmen (lm)

** Nível de Iluminamento ou Iluminância
+ Relação entre o fluxo luminoso pela área de incidência
+ Unidade: Lux
+ Norma da ABNT que indica os níveis de iluminamento de acordo com a atividade a ser realizada no ambiente
+ ISO/CIE-8995-1 (Iluminação de ambiente de trabalho. Parte 1: Interior)

** Índice de reprodução de cores (IRC)
+ Escala de 1 a 10 (ou 100%) que indica as características mais precisas possível das cores de um corpo.

** Eficiência Luminosa
+ Relação entre o fluxo luminoso emitido por uma fonte e sua potência (W)
+ Unidade: lúmens/watt (lm/m)

** Cálculo Luminotécnico (método dos lúmens)
+ Determinar a quantidade de luminárias para se obter o nível de iluminamento adequado para determinada atividade
*** Fatores a serem analisados
+ Área;
+ Altura;
+ Cores de teto, parade e piso;
+ Tipo de luminária;
+ Tipo de lâmpada;
+ Tipo de atividade;
+ Período de manutenção das luminárias/lampadas

* Cálculo Luminotécnico (parte 2)
\[\Phi = \frac{E\cdot S}{Fu\cdot Fdl\]

+ Onde E é lux e S é área
\[\Phi_{LUM} = n\cdot \Phi_{LÂMP}\]
+ Número de luminárias \[=\frac{\Phi_{T}}{\Phi_{LUM}}\]
+ Fu: Fator de utilização da luminária no recinto. Uso de tabela
+ Fdl: Fator de Depreciação da luminária (dado)
+ Refletâncias para uso da tabela de Fu:
+ Teto: Branco = 70%; Claro = 50%; Escuro = 30%
+ Parede: Claro = 50%; Escuro = 30%
+ Piso: Escuro = 10%

* Cálculo do Fu:
\[k = \frac{(A\times B)}{Hlp\cdot (A+B)\]
+ Onde A é comprimento (m), B é largura (m), Hlp é a distância da luminária ao plano de trabalho (m) e k é o índice do recinto

| Teto-   | 70%        | 50%        |
| Parede- | 50%/30%    | 50%/30%    |
| k:      | Piso (10%) | Piso (10%) |
|         |            |            |

+ Exemplo do roteiro: E = 500lux; Fdl = 0,75; h=0,7; Pé direito = 3,5m; Área = 35x20 = 700m²; Teto: Claro (50%); Parede: Claro (50%); Piso: Escuro (10%)
\[Hlp = 3,5-0,7=2,8m\]
\[k = \frac{(35\times 20)}{2,8\cdot (35+20)\]

| Teto-   | 70%        | 50%        |
| Parede- | 50%/30%    | 50%/30%    |
| k:      | Piso (10%) | Piso (10%) |
| 4,0     |            | 0,72       |
| 5,0     |            | 0,76       |

+ Nosso k deu entre dois valores de número (4 e 5), logo para descobrir o valor do fu precisaremos fazer uma continha (interpolação)

\[\frac{5-4}{5-4,55} = \frac{0,76-0,72}{0,76-Fu}\]
\[Fu \approx 0,74\]

* Cálculo Luminotécnico (parte 3)
+ Exemplo da última aula:
+ E = 500 lux; Área: 35x20 m^2; Pé direito: 3,5m; Altura do plano de trabalho: 0,7m; Fator de depreciação: 0,75; Fluxo de cada lâmpada: 2700 lm; Fator de utilização da luminária: 0,74
\[\Phi = \frac{E\times S}{Fu\times Fdl} = \frac{500\times 700}{0,74\times 0,75} = 630630,60 lm\]
+ Cada luminária possui 2 lâmpadas
\[\Phi = 2\times 2700 = 5400 lm\]
+ Número de luminárias:
\[\frac{\Phi_{T}}{\Phi_{LUM}} \approx 117\]
+ Regra para distribuição:
\[x\leq Hlp\]
\[y \leq Hlp\]
+ x e y é a distância entre as luminárias
+ Analisar arranjos "linhas x colunas" para a distribuição do fluxo de forma mais homogênea: 9x13


** Lista cálculo luminotécnico
1) Dados: E = 600 lux; A = 9x6m^2; Pé direito: 4,5m; Plano de trabalho está a 0,75m do chão; Paredes e teto claros, piso é escuro; Fluxo de cada lâmpada: 2300 lm; Fdl = 0,78
\[Hlp = 4,5 - 0,75 = 3,75 m\]

\[k = \frac{9\times 6}{3,75(9+6)} = 0,96\]


\[Fu = \frac{1-0,8}{1-0,96} = \frac{0,36-0,3}{0,36-Fu}\]

\[Fu = \frac{0,2}{0,04} = \frac{0,06}{0,36-Fu}\]

\[Fu = 0,348\]

\[Phi = \frac{E\times S}{Fu\times Fdl} = \frac{600\times 54}{0,78\times 0,348} = 119 363,39 lux\]

\[\Phi_{LUM} = 4600 lm\]

+ Numero de luminárias:
\[\frac{\Phi_{T}}{\Phi_{LUM} \approx 26\]

* Distribuição de luminárias
+ \[X < Hlp\]
+ \[Y < Hlp\]
+ X e Y: Distância entre luminárias
+ Hlp: Distância entre luminária e plano de trabalho
** Exemplo
+ Área: 8x6m^2
+ Quantidade de luminárias: 12
+ Hlp: 2,8m
+ 3x + 2x/2 = 8m (x aqui é a distância entre luminária e parede)
+ 2y + 2y/2 = 6m
+ x = 2m < Hlp
+ y = 2m < Hlp
** Exemplo 1
+ Quantidade de luminárias: 12 luminárias
+ Área: 15 x 20m
+ Hlp: 2,8m
+ 7x + 2x/2 = 20 = 2,5m
+ 5y + 2y/2 = 15 = 2,5m
  48 luminárias (Cálculo exagerado)

* Dimensionamento de condutores
** 3 critérios
+ Critério da seção mínima - para iluminação 1,5mm^2 e para força 2,5mm^2
+ Critério da capacidade de condução - levamos em consideração a corrente pela fórmula \[I=\frac{S}{V}\] e consultamos as tabelas para possivelmente aplicar o fator de correção
+ Critério do limite de queda de tensão

* Dimensionamento de condutores pt2
+ O resultado tem que se enquadrar nos 3 critérios, sendo o maior número mais valido (porque cabe em todos os critérios lol)

** Exercício proposto
+ 5 circuitos -> Fa = 0,6
+ T = 40C -> Fe= 0,87

*** Critério de Capacidade de Condução de Corrente
**** Circuito 1
+ \[I=\frac{S}{V} = I = \frac{2000}{127} = 15.74 A\]
+ \[Ib = \frac{15.75}{(0,6\times 0,87)} = 30,17A\]
**** Circuito 2
+ \[I=\frac{S}{V} = I = \frac{4500}{220} = 20.45 A\]
+ \[Ib = \frac{14.96}{(0,6\times 0,87)} = 28,66A\]
4 mm^2
**** Circuito 3
+ \[I=\frac{S}{V} = I = \frac{7500}{220} = 34.09 A\]
+ \[Ib = \frac{14.96}{(0,6\times 0,87)} = 39,18A\]
6 mm^2
**** Circuito 4
+ \[I=\frac{S}{V} = I = \frac{3000}{380} = 7.89 A\]
+ \[Ib = \frac{14.96}{(0,6\times 0,87)} = 65,31A\]
16 mm^2
**** Circuito 5

* Dimensionamemto de condutores
** Critério do Limite de Queda de Tensão
+ Fórmulas:
  \[\R=\rho\cdot \frac{l}{A}\]

  \[V = R\cdot I + V_{t}\]

  + Equações para determinar as seções dos condutores:

\[Sc = \frac{200\cdot \rho\cdot l\cdot I_{b}}{\Delta V\cdot V}\] (para circuitos monofásicos e bifásicos)

Onde Sc é a seção do condutor em mm^2, $\rho$ é a resistividade do material, l é comprimento do circuito em m, $I_{b}$ corrente de projeto em A e $\Delta V$ é queda de tensão admissível em %

\[Sc = \frac{173,205\cdot \rho\cdot l\cdot I_{b}}{\Delta V\cdot V}\] (para circuitos trifásicos)


+ Exemplo: 1) Um circuito atende a 15 tomadas monofásicas de 100VA. O comprimento total do circuito é 30m. Calcule as seções dos condutores para as seguintes quedas de tensão admissíveis:
a) 5,0%
\[Sc = \frac{200\cdot \frac{1}{56}\cdot 11,81\cdot 30}{5\cdot 127} = 1,99 -> 2,5 mm^2\]
b) 3,5%
\[Sc = \frac{200\cdot \frac{1}{56}\cdot 11,81\cdot 30}{3,5\cdot 127} = 2,84 -> 4 mm^2\]
c) 1%
\[Sc = \frac{200\cdot \frac{1}{56}\cdot 11,81\cdot 30}{1\cdot 127} = 9,96 -> 10 mm^2\]

2) Determine a queda de tensão (%) proporcionada por um condutor de 10mm^2 de um circuito trifásico, 220V, que atende uma carga a 180m do quadro de distribuição. Ib = 30A
\[10 = \frac{173,205\cdot \frac{1}{56}\cdot 180\cdot 30}{\Delta V\cdot 220}\]
\[\Delta V = 7,6%\]
** Limites de Queda de Tensão admissíveis ($\Delta V$)
+ 5\% -> Do ponto de entrega da concessionária em Baixa Tensão (BT) até a última carga
+ 7\% -> Do secundário do transformador da unidade consumidora até a última carga
+ joao.okumoto@ifms.edu.br

*** Exercício 4
+ Queda de tensão admissível $=3\%$
+ Interior de molduras (A1)
+ Temperatura 35C
+ Isolação EPR
+ Ft = 0,96 e Fa = 0,8
**** Circuito 1
+ Critério 1 (Seção mínima): (Circuito de força) -> $2,5mm^2$
+ Critério 2 (Condução de corrente): Dois condutores (Fase + Neutro) -> $1,5mm^2$

\[I = \frac{S}{V}\]

\[I = \frac{1800}{127} = 14,17 A\]

\[I = \frac{14.17}{Ft\times Fa\]

\[I = \frac{14.17}{0,96\times 0,8}\]

\[I = \frac{14.17}{0,768} = 18,45A\]

Seção (de acordo com a tabela 37): $1,5mm^2$

+ Critério 3 (Queda de tensão): -> $15.88mm^2$

\[Sc = \frac{200\cdot \rho\cdot l\cdot I_{b}}{\Delta V\cdot V}\]

\[Sc = \frac{200\cdot 0,0178\cdot 120\cdot 14,17}{3\cdot 127} = \frac{6053,424}{381} = 15.88mm^2\]

**** Circuito 2
+ Critério 1 (Seção mínima): $1,5mm^2$ (Circuito de iluminação)
+ Critério 2 (Condução de corrente): Dois condutores (Fase + Neutro) -> $1,5mm^2$

\[I = \frac{S}{V}\]

\[I = \frac{1650}{127} = 12,99 A\]

\[I = \frac{12,99}{Ft\times Fa\]

\[I = \frac{12,99}{0,96\times 0,8}\]

\[I = \frac{12,99}{0,768} = 16,91 A\]

Seção (de acordo com a tabela 37): $1,5mm^2$

+ Critério 3 (Queda de tensão): -> $18,25mm^2$

\[Sc = \frac{200\cdot \rho\cdot l\cdot I_{b}}{\Delta V\cdot V}\]

\[Sc = \frac{200\cdot 0,0178\cdot 150\cdot 12,99}{3\cdot 127} = \frac{6956,145}{381} = 18,25mm^2\]
**** Circuito 3
+ Critério 1 (Seção mínima): $2,5mm^2$ (Circuito de força)
+ Critério 2 (Condução de corrente): Dois condutores (Fase + Fase) -> $2,5mm^2$

\[I = \frac{S}{V}\]

\[I = \frac{3600}{220} = 16,36 A\]

\[I = \frac{16,36}{Ft\times Fa\]

\[I = \frac{16,36}{0,96\times 0,8}\]

\[I = \frac{16,36}{0,768} = 21,3 A\]

Seção (de acordo com a tabela 37): $2,5mm^2$

+ Critério 3 (Queda de tensão): -> $8,84mm^2$

\[Sc = \frac{200\cdot \rho\cdot l\cdot I_{b}}{\Delta V\cdot V}\]

\[Sc = \frac{200\cdot 0,0178\cdot 100\cdot 16,36}{3\cdot 220} = \frac{5840,51}{660} = 8,84mm^2\]
**** Circuito 4
+ Critério 1 (Seção mínima): $2,5mm^2$ (Circuito de força)
+ Critério 2 (Condução de corrente): Dois condutores (Fase + Fase) -> $6mm^2$

\[I = \frac{S}{V}\]

\[I = \frac{6000}{220} = 27,27 A\]

\[I = \frac{27,27}{Ft\times Fa\]

\[I = \frac{27,27}{0,96\times 0,8}\]

\[I = \frac{27,27}{0,768} = 35,5 A\]

Seção (de acordo com a tabela 37): $6mm^2$

+ Critério 3 (Queda de tensão): -> $26,55mm^2$

\[Sc = \frac{200\cdot \rho\cdot l\cdot I_{b}}{\Delta V\cdot V}\]

\[Sc = \frac{200\cdot 0,0178\cdot 180\cdot 27,27}{3\cdot 220} = \frac{17523,702}{660} = 26,55mm^2\]
+ Queda de tensão admissível $=3\%$
+ Interior de molduras (A1)
+ Temperatura 35C
+ Isolação EPR
+ Ft = 0,96 e Fa = 0,8
**** Circuito 1
+ Critério 1 (Seção mínima): (Circuito de força) -> $2,5mm^2$
+ Critério 2 (Condução de corrente): Dois condutores (Fase + Neutro) -> $1,5mm^2$

\[I = \frac{S}{V}\]

\[I = \frac{1800}{127} = 14,17 A\]

\[I = \frac{14.17}{Ft\times Fa\]

\[I = \frac{14.17}{0,96\times 0,8}\]

\[I = \frac{14.17}{0,768} = 18,45A\]

Seção (de acordo com a tabela 37): $1,5mm^2$

+ Critério 3 (Queda de tensão): -> $15.88mm^2$

\[Sc = \frac{200\cdot \rho\cdot l\cdot I_{b}}{\Delta V\cdot V}\]

\[Sc = \frac{200\cdot 0,0178\cdot 120\cdot 14,17}{3\cdot 127} = \frac{6053,424}{381} = 15.88mm^2\]
*** Exercício 5
+ No interior de canaletas fechadas embutidas no piso (B1)
+ Temperatura 30C
+ Isolação EPR
+ Ft = 0,93 e Fa = 0,7
+ Queda de tensão admissível $=3\%$
**** Circuito 1
+ 6000VA, 220V (3 condutores), L = 200m
+ Critério 1 (Seção mínima): (Circuito de força) -> $2,5mm^2$
+ Critério 2 (Condução de corrente): Dois condutores (Fase + Neutro) -> $6mm^2$

\[I = \frac{S}{V}\]

\[I = \frac{6000}{220} = 27,27 A\]

\[I = \frac{27,27}{Ft\times Fa\]

\[I = \frac{27,27}{0,93\times 0,7}\]

\[I = \frac{27,27}{0,651} = 41,89A\]

Seção (de acordo com a tabela 37): $6mm^2$

+ Critério 3 (Queda de tensão): -> $25,47mm^2$

\[Sc = \frac{173,205\cdot \rho\cdot l\cdot I_{b}}{\Delta V\cdot V}\]

\[Sc = \frac{173,205\cdot 0,0178\cdot 200\cdot 27,27}{3\cdot 220} = \frac{16814,94}{660} = 25,47mm^2\]

**** Circuito 2
+ 9000VA, 220V (3 condutores), L = 250m
+ Critério 1 (Seção mínima): (Circuito de força) -> $2,5mm^2$
+ Critério 2 (Condução de corrente): Dois condutores (Fase + Neutro) -> $16mm^2$

\[I = \frac{S}{V}\]

\[I = \frac{9000}{220} = 45 A\]

\[I = \frac{45}{Ft\times Fa\]

\[I = \frac{45}{0,93\times 0,7}\]

\[I = \frac{45}{0,651} = 69,12 A\]

Seção (de acordo com a tabela 37): $16mm^2$

+ Critério 3 (Queda de tensão): -> $52,55mm^2$

\[Sc = \frac{173,205\cdot \rho\cdot l\cdot I_{b}}{\Delta V\cdot V}\]

\[Sc = \frac{173,205\cdot 0,0178\cdot 250\cdot 45}{3\cdot 220} = \frac{34684,3}{660} = 52,55mm^2\]

* Dimensionamento de disjuntores
+
