#+TITLE: Instrumentação e Controle
#+DESCRIPTION: Instrumentação e Controle - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Primeira Aula
+ O professor Hilton James passou como vai ser as notas da disciplina, de acordo com a seguinte equação
  \[MF=\frac{[(P1\cdot 0,7)+(Ativ. Trab.\cdot 0,3)]+[(P2\cdot 0,7)+(Ativ. Trab.\cdot 0,3)]}{2}\]

Sendo P1 dia 31/03 e sua recuperação dia 07/04 e a P2 sendo dia 09/06 e sua recuperação dia 23/06.

+ Ele também passou seus horários de permanência: 14h30-17h05 (WED), 08h30-10h20 (THU), 18h50-20h20 (FRI) - Salas B206, B102, B204

+ A disciplina vai ser ministrada pelo professor Hilton James na parte prática e a teoria com a professora Gabriele Kavano

+ Horário de PE da professora: 15h35-16h30 (THU)

** O que é instrumentação
+ É a ciência que desenvolve e aplica técnicas de medição, indicação, registro e controle de processos de fabricação, visando à otimização e eficiencia desses processos
+ A instrumentação está ligada e é a base para a automação, pois permite a leitura das variaveis de um processo
+ Também permite o sensoriamento, condicionamento, transformação da informação lida e a atuação em um processo

** Tipos de processos (ponto de vista do tempo e do tipo de operação envolvida)
*** Processo Contínuo
+ A adição da matéria-prima e a saída do produto são contrínuas (no sentido de não ser interrompido). Ex: Refinaria de petróleo
  - Não realizam paradas periódicas (Works 24/7), exceto por paradas progamadas com um periodo maior que 1 ano
  - Esse tipo de industria faz somente um produto
  - Industrias de grande porte

*** Processo em Batelada
+ O processo é alimentado e re-alimentado. O produto é descarregado e inicia-se outro ciclo, sendo o intervalo entre estes curto.
+ Permite vários produtor em uma mesma linha de produção. Ex: Fanta laranja, fanta uva, etc...
+ É um processo descontínuo

*** Processo Discreto
+ Itens separados = produto
+ Não tem dependência de outras etapas como no processo contínuo, ou tanto quanto em batelada
+ Geralmente usa-se robos
+ Industria de automóveis é um exemplo


* Aula 17/02
+ Tivemos que fazer o pré-rascunho de um artigo em trio. Fui com Daniel e Lukas. Obtivemos a seguinte belezinha
#+ATTR_HTML: alt: waterwave :title Primeira atividade prática :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://luispengler.github.io/virtual-notebook/12th-grade/doc/instrumenta1.jpg

* Aula 18/02
** Classes de instrumentos
+ Podem ser divididos em várias categorias
*** Elemento primário/Sensor
+ Capaz de detectar a variação de uma grandeza física e converter um tipo de grandeza que pode ser mensurada por dispositivos eletrônicos. Ex: termometro
+ Esta classe é dividida entre instrumento cego (não apresenta um visor) e instrumento indicador (possui um visor)
+ Normalmente se associa com outros componentes para se tornar um transdutor

*** Registrador
+ Registra as variações de uma ou mais variáveis, guardando as em discos ou fitas de papel e através de displays eletrônicos

*** Conversor
+ Recebe um tipo de sinal e o converte em outro

*** Transmissor/Transdutor
+ Mede uma grandeza física e transmite um sinal padronizado proporcional a faixa de variação da grandeza

*** Controlador
+ Recebe sinais dos transmissores/sensores e com base nisso, faz a correção do sistema acionando os atuadores

*** Atuador/Elemento final de controle
+ Provoca uma mudança em uma variável do processo de acordo com um sinal enviado pelo controlador do processo.

* Aula 24/02
+ Fazer pré-rascunho de um artigo (sozinho), contendo Introdução, Problemática, Objetivo...
+ Aqui está o [[https://luispengler.github.io/virtual-notebook/12th-grade/doc/instrumentacao1/instrumentacao1.pdf][artigo pronto]]

* Aula 25/02
*** Zero Vivo
+ Transmissão de um sinal de 4 a 20mA, com 4 sendo o 0% do nível de água de um recipiente. 20mA representa 100%

** Características dos sistemas de medição
*** Faixa nominal (nominal range)
+ Limite superior e inferior da faixa de trabalho do instrumento

*** Fundo de escala
+ Valor máximo que um instrumento de medida pode medir sem ser danificado

* Aula 03/03
+ O professor fez a correção da atividade entregue anteriormente (aula 24/02)
+ Fomos apresentados o sensor infrared difuse e o infrared retroreflective. Depois fomos pedidos para escolher o melhor desses dois para identificar a passagem de ouro numa linha de trituração e o melhor entre os dois para identificar se há um objeto passando OU NÃO em uma linha de produção.
+ Retro-reflective: Sinal lógico 0 quando nada está passando. Mas existem dois tipos, aqueles que emitem ondas polarizadas e que não. Não polarizados não saberiam diferenciar o seu espelho retro-refletor de um objeto metálico, se este redirecionasse o feixe do emissor diretamente no receptor. Neste caso, objetos metálicos, às vezes, fariam o nível lógico voltar pra 0. Com objetos normais, o nível lógico continuaria sendo 1. É sensível até 7m. No entanto, para o tipo de ondas polarizadas, qualquer objeto que interrompa o feixe, mesmo que este seja metálico (ou até outro espelho!), o sinal lógico vai ser 1. É sensível de 3 a 5,5m.
+ Difuse: A diferença entre este e o anterior, é que usam o alvo para mandar a luz de volta (em vez de um espelho). No entanto, nem todos os alvos são bons em emitir luz de volta e precisam estar mais perto do que alguns para serem detectados. Sensores de proximidade difusos tem um alcance de até 500mm. Qualquer alvo dentro deste alcance vai ser visto, contanto que reflita luz suficiente. Para aplicações menores (com alvos menores), existe o tipo de foco fixo. O foco do emissor e receptor estão no mesmo ponto do espaço, aumentando a sua precisão, mas diminuindo o alcance quando comparados com sensores de proximidade difusos. Alcance de geralmente até 70mm.
+ Aqui está o [[https://luispengler.github.io/virtual-notebook/12th-grade/doc/instrumentacao2/instrumentacao2.pdf][artigo pronto]]

* Aula 04/03
+ Prova semana que vem (atividade avaliativa) até a Aula 3 no moodle
** Tipos de sensores
+ Sensores industriais: Pega uma variável e transforma em outra variável mais conveniente
+ Sesnsores podem ser do tipo discreto e contínuo

*** Sensores discretos
+ Apenas ligado ou desligado
+ Ex: Chave fim de curso

**** Sensores de proximidade discretos
+ Detectar a presença de um determinado objeto e chaves eletromecânicas são atuadas em função disso
+ Usado para detecção de posição, contagem de peças, medição da velocidade, detecção do nível de água e detecção de altura, detecção de forma, detecção de ferramenta

**** Definições Básicas
+ Face sensora: superficie de onde sai campo elétrico ou campo eletromagnético
+ Distância sensora nominal (Sn): Distância teórica que os sensores são específicados. Não significa que ele sempre vai operar nessa faixa.
+ Distância sensora operacional (Sa): Distância segura, em que se considera todas as variáveis de industrialização, temperatura e tensão de alimentação.
\[S_{a}=0,81\cdot S_{n}\]
+ Alvo padrão: É um acionador normalizado para calibrar a distância sensore nominal durante o processo de fabriação do sensor. Este consiste de uma chapa de aço de 1mm de espessura, formato quadrado, mas essas medidas mudam por sensor.
+ Histerese: Diferença entre o ponto de acionamento e o ponto de desligamento. Basicamente a medida (em m, mm, cm, etc) da diferença de desligar ou ligar um sensor

**** Configurações elétricas em corrente contínua
+ Apresentam várias formas de estágios de saída.
+ A configuração elétrica em corrente contínua é bastante usada na automação de processos.
+ Existem dois tipos de transistores de saída
  - Um que comuta o terminal positivo da fonte (PNP)
  - Otro que comuta o terminal negativo da fonte (NPN)
+ Esses tipos de sensores apresentam características que dependem do conhecimento das definições abaixo
  - Normalmente aberto (NO) (NA): O transistor de saída está normalmente cortado, com o sensor desativado, assim a carga está desativada também.
  - Normalmente fechado (NC) (NF): O transistor de saída está normalmente saturado, com o sensor ativado, assim a carga está ativada também.

**** Tipos de sensores de proximidade
***** Indutivos: detectam a proximidade de elementos metálicos sem a necessidade de contato
+ Este gera um campo eletromagnético que é gerado por uma bobina ressonante instalada na face sensora
+ Sua distância sensora operacional depende do tipo de material e é multiplicada por um fator de redução

***** Magnéticos: detectam a proximidade de um imã, atuando de acordo com a sua presença e ausência
***** Capacitivos: detectam a presença de materiais orgânicos, pós, líquidos, entre outros. Assim como objetos dentro de objetos (líquidos dentro de garrafas)
+ Consiste de duas placas paralelas (armaduras) e isoladas por um dielétrico
+ O valor da capacitância pode ser alterado pela aproximação de um objeto
+ Por serem utilizados em uma grande variedade de objetos, geralmente há algum tipo de ajuste de sensibilidade presente na parte traseira do sensor.
+ Permissividade relativa: uma medida do aumento de capacidade de armazenar energia em um meio dielétrico sob efeito de um campo elétrico. Quanto maior esse valor, maior a quantidade de cargas elétricas que o capacitor será capaz de armazenar em suas armaduras.
+ São influenciados pela densidade do meio onde o sensor está instalado, então tomar cuidado com este ambiente

***** Sensores de proximidade fotoelétricos
+ Denomidados de sensores ótpicos, os quais manipulam a luz para detectar a presença de um objeto dentro de uma área delimitada
+ Transmissor: Apenas sensores fotoelétricos ativos o apresentam. Este componente envia um feixe de luz através de um LED. Esses flashes são de alta potência e de curta duração
+ Receptor: Composto por um fototransistor que é sensível à luz emitida pelo transmissor
+ Conversor de sinal: Converte os pulsos de luz do transmissor em sinais elétricos.
+ Estes ainda podem ser
  - Ativos: Necessitam de transmissor e receptor de infravermelho separados
  - Passivos: Apresentam somente receptores pois não emitem ondas infravermelhas

****** Sistema por barreira direta
+ Transmissor e receptor estão em unidades distintas e devem ser dispostos frente a frente
+ Quando houver alguma interrupção, a saída será acionada
****** Sistema por difusão
+ O transmissor e receptor são montados na mesma unidade
+ O acionamento da saída ocorre quando o objeto a ser detectado entre na região de sensibilidade e reflete para o receptor o feixe de luz emitido pelo transmissor
+ É muito eficiente com objetos metálicos, pois depende do índice de reflexão do objeto
+ É calibrado com uma folha de papel branco, apresentando índice de refletividade de 90%
\[S_{a}=0,81\cdot S_{n}\cdot F\]

* Aula 10/03
+ Instrumentamos sensores capacitivos e indutivos com diversos materiais (silicone, joelho de cano pvc, cabo de cobre isolado com borracha)
+ Devemos retomar o trabalho da aula (03/03) com a adição desses dois novos sensores
+ Capacitive Proximity Sensors: They emit an electrical field from the sensing end of the sensor. Any target that can disrupt this electrical field can be dedected by a capacitive sensor. It can detect all types of metal, all types of plastic, wood, paper, glass, and cloth; liquids like water, oil, and paint. It can also detect a material in a nonmetallic container -- but these types have and ajustable sensing range. Same use as the retroreflective sensor (?)
+ Inductive Sensors: Can detect ferrous metal without physical contact, but it can also detect alluminun, brass, and copper, however its sensibility gets decreased by those materials

* Aula 11/03
** Sensores de proximidade ultrassônicos
+ Emprega frequências fora do espectro de audição humana, determinando a distância de objetos (proximidade)
+ A detecção acontece quando a onda bate sobre um objeto e produz um eco
+ O tempo de repetição do eco é medido, sendo convertido em um sinal elétrico.
+ Existe uma repetição desses pulsos de onda mecânica de 1 a 100Hz.
*** Vantagens
+ Detcção sem contato direto
+ Detecção idependente da cor
*** Desvantages
+ Dificuldade de detecção se há muitas irregularidades no objeto
+ Esse sensor é relativamente lento (porque usa som)
+ Custo maior comparado aos fotoelétricos
+ Podem ser influenciados pela temperatura (porque a velocidade do som muda de acordo com a temperatura)
+ Dificuldade no uso de vários sensores ultrassônicos próximos (por causa da interferência)
** Sensor óptico de posição (encoder)
+ Detectam a posição de um objeto com respeito a um ponto de referência
+ Podem medir distâncias lineares quanto angulares
+ Funciona convertendo o movimento ou posição angular em uma série de pulsos.
*** Encoder absoluto
+ Definimos a posição absoluta do encoder através de um código
+ O código mais utilizado é o binário, mas pode ser o código de Gray
*** Encoder Incremental
+ Possui apenas uma trilha com dentes igualmente espaçados
+ A resolução é dada pela relação pulso/revolução (chamado de PPR) - Quantos pulsos de luz por cada volta?
+ Podem ser dividos em simples e quadratura
* Aula 17/03
+ Fizemos a instrumentação de encoder incremental (rotary encoder)

* Aula 18/03
+ Definição da data da recuperação da primeira prova (24/03-27/03)
+ Definição da data da P2 (07/04-10/04)
+ Definição da data da recuperação da P2 (22/04-24/04)
** Medidores de pressão
*** Coluna de líquido
+ O deslocamente de um líquido em função da pressão que é aplicada nas extremidades do tubo
+ Pode ser feito do tipo U, tipo reservatório (ou coluna reta vertical), tipo inclinado (ou coluna reta inclinada)
+ Eram muito utilizados em laboratório, mas foram subtituidos por instrumentos mais precisos
*** Manômetro de pressão elástico
+ Manômetro tubo de Bourdon tipo C
+ Manômetro tubo de Bourdon tipo espiral - utilizado para pressões maiores e por causa do seu formato minimiza os efeitos da turbulência
+ Manômetro tubo de Bourdon tipo helicoidal - utilizado para pressões maiores que o espiral
+ Manômetro tipo Fole
+ Manômetro tipo Diafragma
*** Medidor de pressão eletrônicos
+ Sensor de pressão piezoelétrico
+ Sensor de pressão piezorresistivo (Strain Gauge) - feito de materiais que alteram sua resistência quando a força é aplicada
+ Sensor de pressão capacitivo - a armadura móvel, ao sofrer uma variação de pressão, altera o valor da capacitância
+ Sensor de pressão indutivo
** Medidor de nível
+ As medidas de nível permitem avaliar quantidades em tanques que contêm líquidos ou sólidos
+ É chamada de monitoramento contínuo, quando a saída é proporcional ao nível que se pretende medir
+ É chamada de monitoramento discreto, quando indica uma faixa ou presença de material armazenado
+ Medida de nível direta: realizada como referência o nível superior
+ Medida de nível indireta: Usado outras grandezas físicas (pressão, empuxo, radiação, etc) para indicar o nível indiretamente

* Medição de Vazão
+ Vazão é a quantidade volumétrica ou mássica de um fluido que passa através de uma seção transversal
+ Essa medição é utiliazda para garantir que determinados ingredientes são fornecidos a uma taxa adequada durante o processo de mistura
+ Para evitar uma vazão elevada, que pode ocasionar em explosões

** Vazão volumétrica
+ Quantidade de volume por tempo
\[Q=\frac{V}{t}\]

** Vazão mássica
+ Quantidade de massa por tempo
\[Q_M=\frac{M}{t}\]

** Perda de carga localizada
+ Ocorre em trechos da tubulação onde há presença de acessórios, i.e. válvulas, curvas, derivações, registros ou conexões, bombas, turbinas, etc.
+ A presença desses acessórios contribui para a alteração de módulo ou direção da velocidade média do escoamento, consequentemente alterando a pressão no local (contribui para aumento do número de reynolds)
+ Menor a perda de carga localizada, menor a queda de pressão

** Medição da vazão por pressão diferencial
+ É inserido em uma tubulação um dispositivo capaz de gerar uma diferença de pressão que será detectada através de tomadas de pressão
+ Tem-se uma variação da diferença de pressão em função da vazão do sistema
+ Se aumentarmos o valor da vazão aumentamos o valor da pressão diferencial, essa relação é direta porém não é linear

*** Dipostivos

**** Placa de Orfício
+ Esse elementos consistem de uma placa que será inserida dentro da tubulação e essa placa irá gerar uma redução na passagem do fluido
+ É um dos elementos empregados para medir pressão diferencial de construção, possui manutenção e troca mais simples, mas com alta perda de carga
+ Geralmente são fabricadas com aço inox, monel, latão, etc., dependendo do fluido
+ Existem outros tipos de placa (concêntrico, excêntrico, segmentado), a serem utilizados em outros fluidos (líquidos, gases e vapor sem sólidos em suspensão; com sólidos em suspensão; fluidos viscosos e com alta percentagem de sólidos em suspensão; respectivamente)
+ Existem outros tipo de bordo (o formato interno do orificio) para essas placas de orifício. Estes são bordo quadrado (utilizado em tubulações com diametro maior que 6 polegas), bordo arredondado (utilizado em fluidos altamente viscosos), bordo com entrada cônica (para uso geral)

**** Tubo de Venturi
+ Apresenta uma redução de seção que resulta em aumento de velocidade e pressão menor
+ Assim pode-se medir a pressão entre os pontos P2 e P1
+ A recuperação de pressão em um tubo Venturi é eficiente pois melhora o restabelecimento de pressão, favorecendo fluidos que carregam sólidos em suspensão
+ Produz um diferencial menor que uma placa de orifício, mas o alto custo restringe a sua utlização e apresenta uma perda de carga considerável

**** Bocal de vazão
+ Objeto no formato cônico que é inserido no interior da tubulação
+ É utilizado em aplicações com fluidos muito abrasivos e corrosivos
+ Possui uma perda de carga entre o tubo de orificio e tubo de venturi

**** Tubo de Pitot
+ Consiste em um tubo de pequeno diametro com uma abertura em sua extremidade, voltada a direção de fluxo de um fluido
+ Se medirmos a pressão estática com outro tubo, podemos calcular a velocidade como função da diferença de pressões
+ A diferença de pressão total e a pressão estática da linha nos dará a pressão dinâmica, a qual é proporcional ao quadrado da velocidade
+ Possibilita o funcionamento de um dos mais importantes instrumentos de uma aeronave, o velocímetro

** Medição da vazão do tipo Turbina
+ Constituido por um rotor montado na tubulação, que possui aletas que giram durante a passagem de fluido na turbulação
+ Um sensor de efeito Hall capta a passagem das hélices da turbina
+ a frequência dos pulsos gerados é proporcional à velocidade do fluido
+ É um dos mais flexíveis e universais métodos de medidas de vazão
+ A perda de carga é equivalente a de um trecho reto de tubulação, pois não apresenta obstrução
+ Utiliza a Lei de Faraday de Indução Magnética, onde uma tensão é induzida em um condutor que se move em um campo magnético
+ Essa tensão induzida é detectada e medida por um par e eletrodos e ela é diretamente proporcional à velocidade do fluxo
+ A desvantagem desse medidor restringe-se à necessidade do fluido ser condutivo

** Medição de vazão do tipo Vortex
+ Contém um obstáculo após o qual ocorre um rastro de vórtices
+ A frequência f do rastro de vórtices é proporcional à velocidade
+ À medida que a velocidade do fluxo aumenta, a frequência oscilação também aumenta.
+ A medição de vazão é feita pela medição indireta de velocidade do fluido

** Medidor de vazão ultra-sonico
+ Emite um sinal ultra-sonico e conta o tempo de resposta, relacionado-o com a vazão.

* Medição de temperatura
** Termomêtros à dilatação de líquidos/gases
+ Normalmente não serão utilizados em sistemas produtivos automatizados
+ Podem ter o corpo metálico ou de vidro, onde está o bulbo há a concentração do líquido/gás
+ Também pode haver o tubo capilar, que é onde o fluido se deslocará

** Termomêtro bimetálico
+ Consiste de lâminas de coeficiente de dilatação linear diferente, as quais são unidas a fim de proporcionar um movimento resultante
+ Ao variar a temperatura, as lâminas apresentarão uma curvatura proporcional que pode ser empregada para indicar temperatura
+ O mais empregado é o da lâmina helicoidal, sendo sua faixa de trabalho de -50C a 800C, sendo sua escala bastante linear e precisão de mais ou menos 1%

** Termopar
+ São largamente utilizados em processos produtivos
+ Um termopar consiste de dois metais, ou ligas, diferentes, unidos por uma junção soldade, chamada de junta quente ou de medição
+ As extremidades dos fios, chamas de junta fria ou referência (JR) são levadas a um medidor de fem, formando um circuito elétrico.
+ Ao ser submetido a uma temperatura diferente da outra extremidade, o termopar produz uma tensão proporcional à variação de temperatura em seus terminais
+ Quatro efeitos conhecidos ocorrem quando junções de materiais distintos são mantidas a temperaturas diferentes: Seebeck, Peltier, Thomson
+ Efeito termoelétrico de Seeback: Dois condutores quando estão submetidos a temperatuas diferentes na JR e na JM surge uma fem nas suas extremidades, representado pelo voltímetro V. O coeficiente de Seeback é a relação entre a tensão e temperatura (medida em mV/C)
+ Efeito termoelétrico de Peltier: Quando uma corrente elétrica i flui na junção entre dois metais diferentes, calor é gerado ou absorvido nesse local em quantidade proporcional à corrente. O circuito poderá gerar ou absorver calor, dependendo do sentido da corrente. Portanto, poderá ser gerado a fem, tanto no aquecimento, como no resfriamento da junção, porém com sentidos opostos de condução
*** Classificação dos termopares
**** Tipo básico
+ São os de maior uso industrial
+ Podem ser empregados em atmosferas inertes, oxidants ou redutoras
+ Os fios são de custo relativamente baixo e sua aplicação permite um limite maior de erro (incerteza maior)
+ Exemplos: Termopar tipo T (cobre-constantan), tipo J (ferro-constantan), tipo E (cromel-constantan), tipo K (cromel-alumel), tipo N (nicrosil-nisil)

**** Tipo nobre
+ São chamados nobres por usar a platina como elemento básico
+ Apresentam uma alta precisão devido à homegeniedade e pureza dos fios e podem ser usados em altas temperaturas
+ Exigem instumentos receptores de alta sensibilidade devido à baixa potêNcia termoelétrica
+ Exemplos: Termopar tipo S (platina/rhódio 90/10), tipo R (platina/rhódio 87/13), tipo B (platina-rhódio 70/30 platina-ródio 94/6)

**** Tipo especial
+ São termopares específicos desenvolvidos para atender a aplicaçẽos restritas que não podem ser atendidas pelo tipo básico e nobre
+ Exemplos: Termopar (Tungstênio/Rhênio), termopar (ouro/ferro-chromel)

**** Termopar convencional
+ A junta metálica do termopar pode ser exposta ao meio ou protegida
+ Os termoelementos são acomodados em isoladores cerâmicos, usualmente denominados missangas, as quais apresentam alta condutividade térmica e também alta resistência de isolação

**** Termopar com isolação mineral
+ O termopar é protegido por uma bainha externa metálica tendo em seu interior um pó isolante de óxido de magnésio
+ A durabilidade do  termopar depende da resistência à corrosão da sua bainha e não da resistência à corrosão dos condutores

** Termorresistências (RTD - Resistance Temperature Detector)
+ É um dispositivo de medidade de temperatura resistivo, RTD, sendo um resistor que varia sua resistência em função da temperatura
+ Normalmente o sensor é construído em um filme metálico ou em um pequeno enrolamento à partir de um fio muito fino
+ Os principais metais empregados são ligas compostas por niquel, cobre, ou platina com várias faixas de medidade e de custo
+ Exemplo: Pt100, Pt1000

* Diagrama P&I
+ A norma da ISA é a simbologia/codificação mais utilizada na área de instrumentação e controle de processos padronizados.
+ Cada instrumento serâ identificado por um conjunto de letras (identificação funcional) e números (identificação da malha de controle).
* Simbolos gerais
+ Instrumento discreto montado no painel principal (circulo com traço)
+ Instrumento discreto montado no campo (só circulo)
+ Instrumento compartilhado montado no painel principal

* Democratização do talvez
+ Todos podem falar "talvez", sem distinção de gênero e cor
+ Na duvida, sempre diga "talvez" e nunca diga nunca
+ Ninguém pode te forçar a te dizer sim ou não, se isso acontecer diga "talvez"
+ "Talvez" também pode ser referido como "Maybe", "Perhaps", "Villeicht", mas são versões menos usadas da palavra

* Ações de Controle
+ PID significa propocional, integral e derivativo
+ O objetivo de um PID é aproveitar as características de cada uma das ações, que funciona melhor em regimes transitórios e permanentes
+ PID consideram uma ação presente, passada e futura
