#+TITLE: Meio Ambiente e Energias Renováveis
#+DESCRIPTION: Meio Ambiente e Energias Renováveis - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Aula (03/03)
** Sistema Off-grid
+ Ideal para lugares onde a energia elétrica não chega
+ Economicamente inviável, por conta dos elevados custos e vida útil das baterias reduzidas
+ Todo projeto deve ser sobredimensionado, considerando demanda diária e capacidade de pico (todos aparelhos ligados), assim projetando as placas para funcionar no pior cenário, desperdiçando energia gerada.

** Sistema On-grid
+ Painel solar + Inversor + Medição
+ O medidor precisa ser trocado (para modelo bidirecional), mas a troca do medidor é coberta pela concessionária

** Formas de geração distribuida
*** até 70Kw (microgeração)
+ Altamente desburocratizada
+
*** de 70Kw à 5Mw (minigeração)
+ É necessário um estudo de rede

** Módulo Solar Fotovoltaico
+ São células de aprox. 0,65V ligadas em série
+ Quanto mais luz, menos calor = mais energia
+ Pensar no inversor de acordo com a tensão máxima e mínima das suas placas, pois com variações de temperatura para uma mesma luminosidade, a tensão varia. Isso pode tirar o inversor da rede.

** Circuito Equivalente de um paniel solar fotovoltáico
+ Esquematizado no meu caderno (lol)
+ Não existe um diodo de verdade lmao
+ Rp = Resistência Paralela -> Fulgas internas
+ Rs = Resistência Série -> Resistências internas e dos condutores
+ Dp = Diodo Paralelo
*** Dados no datasheet
+ Short-circuit current: Corrente de curto circuito (dica se estiver com defeito)
+ Open-circuit voltage: Tensão de circuito aberto (desconectado) (operação nos dias frios)

** Curva I-V
+ Tensão e corrente variam
+ 3 tecnologias para inversores identificar o ponto de máxima potência (MPPT = Rastreamento de ponto de máxima potência)
+ Abaixo há um gráfico IxW
#+ATTR_HTML: alt: waterwave :title Curva T-W :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://luispengler.github.io/virtual-notebook/12th-grade/doc/meioambiente1.png

** Formas de conexão dos painéis
+ Sistemas em baixa tensão com micro inversor
+ Ligar os painéis em série -> aumentar a tensão
+ Ligar os painéis em paralelo -> aumentar a corrente

*** String: Painéis em Série
+ Maior eficiência, menor o custo
+ Alta tensão DC
+ Maior possibilidade de falhas em projetos
+ Problemas em um painel afetará toda a string

*** Array: Série paralelo
+ Menor custo para instalação
+ Único MMPT para todos os painéis, acentuando as perdas em caso de falha de algum paniel
+ Protação contra curto circuito

** O problema das sombras
+ A sombra desvia a energia gerada para a resistência, que é o unico condutor fechado, assim sobreaquecendo o painel
+ As sombras paricias são piores, porque se fossem totais, a célula no escuro sairia da geração, minimizando os efeitos da sombra.

* Arco elétrico - Limpeza dos módulos
+ Um dos maiores riscos em UFV;
+ Pode ser difícil de extinguir;
+ Um incêndio pode ser apagado, o arco elétrico não

** Possíveis causas
+ Degradação da isolação, devido à exposição aos raios UV;
+ Rachaduras no isolamento, devido à variações de temperatura;
+ Degradação do isolamento devido ao envelhecimento;
+ Danos ao isolamento causado por roedores, insetos, pássaros, etc;
+ Danos ao isolamento durante a instalação;
+ Danos ao isolamento por trabalhos de construção;
+ Conexões soltas;
+ Corrosão de junções
+ Falha nos isoladores CC;
+ Entrada de água em cabos, eletrodutos, caixas de proteção CC,

** Limpeza dos painéis
+ Realizada a cada 3 meses, ou quando a capacidade de geração cair além de 15%;
+ Desligar completamente a UFV: AC e CC;
+ Não utilizar lavadoras de alta pressão;

* String box
+ Proteção contra curto somente em array maior que 3 strings
+ Um circuito para cada MPPT do inversor
+ Seccionamento AC/DC
+ Proteção contra Surto
+ O inversor que tem DPS interno, chama-se string inverter

* Cabeamento
+ Resistência à intempéries, altas temperaturas e irradiação UV;
+ Isolação para 1,5KV;
+ Cabo estanhado;
+ Dupla isolação;
** Norma
+ Calculas o cabeamento trecho a trecho
+ Queda máxima em toda a extensão: 3%
+ Não usar o critério de 5% da NBR5410

** Proteção e Manobra
+ Arranjo fotovoltáico, proteções CC, inversor, Proteções CA, REDE
** Proteção CC
+ Fusíveis CC - por string
+ Chave Secionadora CC geral ou,
+ Disjuntores CC
+ DPS CC (dispositivos de proteção surtos)
** Proteção CA
+ Disjuntores CA
+ DPS CA (Dispositivos de Proteção Surtos)
+ Chave Secionadora CA (DSV) - opcional

* Projeto de sistemas on-grid
1. Análise de fatura - consumo em kWh durante um período de 1 ano, fazendo uma média - A potência máxima que vc pode instalar é a demanda - Isso vai determinar o tipo do projeto (micro ou mini geração)
2. Algumas análises
   a) Análise de sombreamento
      + Não instale pro sul idiota (aproveitamento coco).
      + Cuidado com os postes!
      + Usar camera SLR, ou celular tirando foto a cada 5min (timelapse)
      + Pegar a potência em W/m^2 em um mapa solar imétrico e os horários de sol de pico
      + Consultar a disponibilidade anual para conseguir o fator que vai ser usado para
      + Colocar o painel inclinado conforme sua latitude, não colocar o painel em menos de 10º de inclinação

   b) Oscilações na rede elétrica
      + Ligou o chuveiro e oscilou a luz, não vai funcionar! (troca as merda dos cabos)
3. Calcular horas de sol pleno (HSP)
      + Hora de Sol Pleno (HSP) é uma grandeza que representa a quantidade de horas em que a irradiância solar seria constante de 1000W/m^2
      + Em campo grande é uns 5,4h HSP
4. Definir o inversor: mono, bi ou trifásico
5. String box
6. Plano de manutenção: Ponto bônus

+ A conta:
  - Consumo a compensar: 300kWh
  - Consumo no dia: 300/30 = 10kWh
  - HSP = 5,4h (CG) -> 10kWh/5,4h = 1,85kW
  - Escolha um painel, neste exemplo usaremos um painel solar fotovoltaico anauger com 340Wp monocristalino, Tensão MPP = 35,7V, Corrente MPP = 9,52 A; Tensão de circuito aberto MPP = 44,6V
  - Número de paineis = 1,85kW/340 = 5,44 painéis; agora dividimos pelo fator de correção 5,44/0,923 = 5, 89 = 6 painéis
  - Inversor para 1,8kW (como não existe, usaremos um de 2kW); Para calcular a tensão de circuito aberto = número de paineis x tensão de circuito aberto MPP = 6x44,6 = 268V; Tensão de ponto máximo = 6 x 35,7 = 214V; Um inversor que atende os requisitos é o Mic 2000TC

* Erros comuns em instalações fotovoltaica
+ Causa: engenheiros e técnicos sem capacitação especifica;
+ Dificuldade em monitorar o sistema;
+ Consequência: danos permanentes e graves às instalações, pessoal e material;
+ Inversores suportam sobrecarga de até 20%, mas algumas empresas prestadores fornecem um inversor 20% menor, sempre operando em sobre carga;
+ Isso encurta a vida útil do equipamento caso não esteja instalado em sala refrigerada;
+ Desperdício da capacidade de geração dos módulos
+ Andar sobre os painéis - módulos não são projetados para suportar peso frontal
+ Proteções CA e CC em uma mesma caixa de junção - não pode pela norma
+ Módulos com diferentes orientações em uma mesma string - MPPT não encontra o ponto de máxima potência, dando uma considerável perda na geração
+ Módulos instalados em áreas sujeitas a sombras parciais ou totais
+ Falta de equipotencialização e aterramento - Colocar isolação galvânica
