#+TITLE: Pneumática e Hidráulica
#+DESCRIPTION: Pneumática e Hidráulica - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Mecânica dos Fluidos
+ Parte da mecânica que se dedica à análise do comportamento dos líquidos e gases
+ Fluídos não têm forma própria, assumen o formato do recipiente

* Massa específica
+ Fluídos incompressíveis têm \[\rho\]

* Peso específico
\[\gamma=\frac{G}{V}=\frac{m\cdot g}{V}=\rho \cdot g\]

* Peso específico relativo para líquidos


* Tensão de cisalhamento
\[\tau=\frac{Ft}{A}=\frac{N}{m^2}\]

* Lei de Newton da Viscosidade
+ Proporcionalidade entre a tensão de cisalhamento e o gradiente da velocidade
\[\tau=\mu\cdot \frac{dv}{dy}=Pa\cdot s; \frac{N\cdot s}{m^2}; Poise\]

+ Quanto maior o \[\mu\] mais a facilidade de escoar

* Viscosidade cinemática (v)
+ Propriedade definida a partir da viscosidade absoluta pela massa específica
\[V=\frac{\mu}{\rho}\]
+ Molécula mais simples = menos viscoso
+ Gás mais quente = mais viscoso

* Estática dos fluidos
+ Estudo do fluido em repouso
+ Hidrostática é outro termo utilizado para os estudos dos fluidos em repouso
+ Em vasos comunicantes, o nível é o mesmo, independente da forma
+ A pressão é descrita como a força normal aplicada sobre uma superfície
\[P=\frac{F_n}{A}\]
+ Onde \[P\] é a pressão em Pascal, \[F_n\] força normal em N, e \[A\] área em \[m^2\]
+ Não se deve confundir pressão com força, pois pressão é simplesmente força pela área (vai se ferrar se tu não sabe disso)

** Teorema de Stevin
\[P_n-P_m=\gamma\cdot h = \gamma\cdot (Z_m-Z_n)\]
+ Na diferença de pressão entre dois pontos não interessa a distância entre eles, mas a diferença de cotas;
+ A pressão dos pontos num mesmo plano ou nível horizontal é a mesma;
+ O formato do recipiente não é importante para o cálculo da pressão em algum ponto
+ Se a pressão na superfície de um líquido num recipiente for nula, a pressão num ponto à profundidade h dentro do líquido será dada por:
\[P=\gamma\cdot h\]
+ Nos gases, como o peso específico é pequeno, se a diferença de cota entre dois pontos não é muito grande, pode-se desprezar a diferença de pressão entre eles
\[P_A\aprox P_B\aprox P_C\aprox\]

** Lei de Pascal
+ A pressão aplicada num ponto de fluido em repouso transmite-se integralmente a todos os pontos do fluido
** Carga de Pressão
+ Pressão em um certo fluido em unidade de comprimento
\[\frac{P}{\gamma}=h\]

** Escalas de pressão
+ Pressão absoluta: A pressão é medida em relação ao vácuo ou zero absoluto
+ Pressão efetiva: A pressão é medida adotando-se a pressão atmosfera como referência
+ Pressão atmosférica: Também chamada de pressão barométrica e varia com a altitude
\[P_{abs}=P_{ef}+P_{atm}\]
*** Unidades de pressão
+ As unidades de pressão podem ser dividas em três grupos
+ Unidades de pressão: \[\frac{kgf}{m^2};\frac={kgf}{cm^2};\frac{N}{m^2} ou Pa; \frac{daN}{cm^2} ou bar;\]
+ Unidades de carga de pressão: mmHg (milímetros de coluna de mercúrio); mca (metros de coluna de água); cmca (centímetros de coluna de água)
+ Unidades definidas: atm (atmosfera)
+ Conversão: 1 atm = 760 mmHg = 101.203 Pa = 101,23 kPa = 10.330 kgf/m^2 = 1,033 kgf/cm^2 = 1,01 bar = 14,7 psi = 10,33 mca

* Cinemática dos fluidos
+ A cinemática dos fluídos trata do estudo do movimento dos fluidos sem considerar as forças que estão atuando.
+ O regime de movimento dos fluidos são divididos em:
  - Regime Permanente - não varia conforme o tempo
  - Regime Transiente (variado) - varia conforme o tempo
+ O regime permanente não tem as propriedades afetadas pela variação pelo tempo
+ O regime variado é aquele em que as propriedades do fluido vvariam em cada ponto com o tempo
+ Osborne Reynolds descobriu 3 padroes de escoamento:
  - Escoamento Laminar
  - Escoamento de transição
  - Escoamento Turbulento
+ Escoamento laminar: as partículas do fluido se deslocam na forma de um fileto reto e contínuo em uma direção longitudinal
+ Escoamento turbulento: as partículas do fluido se deslocam também em uma dimensão transversal, além da longitudinal
** O número de Reynolds (Re)
+ \[Re=\frac{\rho\cdot v\cdot D}{\mu}=\frac{v\cdot D}{\ni}\]
+ Onde:
\[\rho = massa específica\]
\[v = velocidade do escoamento\]
\[D = diametro do tubo\]
\[\mu = viscosidade dinamica\]
\[\ni = velocidade cinemática\]

+ Escoamento laminar
\[Re\le 2000\]
\[2000\lt Re \lt 2400\]
\[Re\ge 2400\]

** Vazão em volume
+ \[Q=\frac{V}{t}=\frac{20L}{10s}=2L/s\]
+ Relação entre a vazão em volume a velocidade do fluido
+ No intervalo de tempo t, o fluido se desloca através da seção da área A, a uma distância S.
+ Logo temos que:
\[Q=\frac{V}{t}=\frac{s\cdot A}{t}\]
\[v=\frac{s}{t}\]
\[Q=v\cdot A]

** Vazão em massa
\[Q_m=\frac{m}{t}\
pesquisa sobre m ponto, coloca um ponto em cima do m e isso significa que é pelo tempo
\[Q_m=\frac{\rho\cdot A\cdot S}{t}=\rho\cdot A\cdot v = \rho\cdot Q\]
+ Quando ocorre o escoamento de um fluido ao longo de um tubo, a vazão mássica vai ser a mesma em qualquer ponto do tubo
+ No entanto, a equação da vazão volumétrica não seria igual, pois em fluidos compressíveis, a alta compressão ferra tudo
+ Volumétrica só é igual a entrada e saída quando for fluido incompressível
+ Exemplo: Um gás escoa em regime em regime permanente no trecho de tubulação da figura. Na seção, tem-se \[A_1=20cm^2\], \[rho_1 = 4kg/m^3\], \[v_1=30m/s\]. Na seção \[A_2 = 10cm^2\] e \[\rho_2 = 12kg/m^3\]. Qual é a velocidade na seção
\[Q_{m1}=Q_{m2}\]
\[\rho_1\cdot v_1\cdot A_1 = \rho_2\cdot v\cdot A_2\]
\[v_2 = v_1\cdot \frac\]

** O efeito Venturi
+ A velocidade aumenta de acordo com a redução da área da seção transversal
+ A pressão diminui de acordo com a redução da área da seção transversal
+ Exemplo: O venturi é um tubo convergente/divergente, como é mostrado na figura. Determinar a velocidade na seção mínima (garganta) da área 5cm^2, se na seção de entrada da área 20cm^2 a velocidade é 2m/s. O fluido é incompressivel.
\[V_e\cdot A_e = V_G\cdot A_G\]
