#+TITLE: Socilogia 3
#+DESCRIPTION: Sociologia 3 - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* 05/07

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style float:left;margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/virtual-notebook/12th-grade/doc/quadroinicialsocilogia3.png

* 12/07
** Sociologia do trabalho
+ Émile Durkheim: (funcionalista): Divisão social do trabalho é um fato social presente em todo tipo de sociedade. Há sociedades com maior ou menor divisão social do trabalho, mas em todas elas são encontradas funções diferenciadas entre os indivíduos. Na sociedade capitalista o trabalho é pensado como uma atividade fundamental, que é exercida pelos trabalhadores. Livro: "A divisão social do trabalho".

+ Max Weber: Para esse autor, não há algo em comum ou geral em todas as sociedades, pois cada sociedade obedece a sua situação histórica exclusiva. Livro: "A ética protestante e o espírito do capitalismo"

+ Karl Marx: O trabalho é visto como a essência do ser humano, existindo dois tipos de trabalho: TRABALHO CONCRETO (valor de uso) X TRABALHO ABSTRATO (valor de troca)

* 19/07
+ Para Marx, o trabalho é a essência humana e o trabalho abstrato seria alienação

* 02/09
** Mais valia
+ A mais valia representa a /disparidade entre o salário pago e o valor produzido pelo trabalho/. Dessa maneira, ela pode ser entendida como o trabalho não pago, ou seja, são horas que o trabalhador cumpre o valor que gera pelos quais não é remunerada. A alienação exerce um papel fundamental na exploração da mais valia. O afastamentodo trabalhador do produto final de seus trabalho é o que possibilita a divisão do trabalho em TRABALHO NECESSÁRIO e TRABALHO EXCESSIVO.

** Mais valia absoluta
+ A mais valia absoluta é prolongar a jornada de trabalho para além do tempo necessário. Ou seja, aumenta-se a jornada de trabalho sem que o salário tenha um aumento
+ Dia de trabalho = 12 horas -> trabalho necessário = 6 horas, trabalho excedente = 6 horas
+ Aumenta a jornada de trabalho = +2 horas
+ Dia de trabalho = 14 horas -> trabalho necessário = 6 horas, trabalho excedente = 8 horas
+ Ex: Aumenta a carga horária sem aumentar o salário

** Mais valia relativa
+ Também é possível aumentar a exploração de mais valia sem alterar o número de horas trabalhadas. Isso pode ser feito por meio de melhorias nos processos técnicos de trabalho, que aumentam a produtividade. Adquirir máquinas que tornem o trabalho mais rápido ou organizar a disposição dos trabalhadores na fábrica de modo mais eficiente.
+ Ex: Mantem ou até reduz sua jornada de trabalho, mas sua produção aumenta nesse período

+ Pesquisar os livros que cada um escreveu
