#+TITLE: Socilogia 3
#+DESCRIPTION: Sociologia 3 - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* 05/07

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style float:left;margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/virtual-notebook/12th-grade/doc/quadroinicialsocilogia3.png


* 12/07
** Sociologia do trabalho
+ Émile Durkheim: (funcionalista): Divisão social do trabalho é um fato social presente em todo tipo de sociedade. Há sociedades com maior ou menor divisão social do trabalho, mas em todas elas são encontradas funções diferenciadas entre os indivíduos. Na sociedade capitalista o trabalho é pensado como uma atividade fundamental, que é exercida pelos trabalhadores. Livro: "A divisão social do trabalho".

+ Max Weber: Para esse autor, não há algo em comum ou geral em todas as sociedades, pois cada sociedade obedece a sua situação histórica exclusiva. Livro: "A ética protestante e o espírito do capitalismo"

+ Karl Marx: O trabalho é visto como a essência do ser humano, existindo dois tipos de trabalho: TRABALHO CONCRETO (valor de uso) X TRABALHO ABSTRATO (valor de troca)

* 19/07
+ Para Marx, o trabalho é a essência humana e o trabalho abstrato seria alienação

* 02/09
** Mais valia
+ A mais valia representa a /disparidade entre o salário pago e o valor produzido pelo trabalho/. Dessa maneira, ela pode ser entendida como o trabalho não pago, ou seja, são horas que o trabalhador cumpre o valor que gera pelos quais não é remunerada. A alienação exerce um papel fundamental na exploração da mais valia. O afastamentodo trabalhador do produto final de seus trabalho é o que possibilita a divisão do trabalho em TRABALHO NECESSÁRIO e TRABALHO EXCESSIVO.

** Mais valia absoluta
+ A mais valia absoluta é prolongar a jornada de trabalho para além do tempo necessário. Ou seja, aumenta-se a jornada de trabalho sem que o salário tenha um aumento
+ Dia de trabalho = 12 horas -> trabalho necessário = 6 horas, trabalho excedente = 6 horas
+ Aumenta a jornada de trabalho = +2 horas
+ Dia de trabalho = 14 horas -> trabalho necessário = 6 horas, trabalho excedente = 8 horas
+ Ex: Aumenta a carga horária sem aumentar o salário

** Mais valia relativa
+ Também é possível aumentar a exploração de mais valia sem alterar o número de horas trabalhadas. Isso pode ser feito por meio de melhorias nos processos técnicos de trabalho, que aumentam a produtividade. Adquirir máquinas que tornem o trabalho mais rápido ou organizar a disposição dos trabalhadores na fábrica de modo mais eficiente.
+ Ex: Mantem ou até reduz sua jornada de trabalho, mas sua produção aumenta nesse período

+ Pesquisar os livros que cada um escreveu

* Redação
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa= 4.4 linhas, então escreve 6 linhas dessa

* Apresentação
** Historic
+ rapid growth of petroleum in 1973, but resulted in bad agricultural production
+ populatin had to import rice for cosmetic consumption
+ in late 90s, goverment privatized many state-run enterprises - communication, power, transportation
+ beggining of 21st century, nigeria continued in crisis so it borrowed money
+ then it had to increase taxes, and do spending cuts, but much of the national bugdet was needed for debt repayment
+ corrupt government disrupted the debt payment, and people were getting poorer
+ Paris Club forgave their debt in 2006
** Agriculture
+ Nigeria has no shortage of arable land, but access is difficult: prohibition to sell family land, desertification in north
+ Between 20-50% of all nigerians live from agricultural production
+ Environmental deteriation, inferior shortage facilities, poor transport system, lack of investment capital -> low productivity, stagnated agriculture
+ Population growing rapidly and urbanization accelerating, the food deficit continues to worsen
** Food
+ yams, taro, cassava, sorghum, millet, cowpeas, corn, rice, oil palm, cacao, rubber trees, peanuts, cotton
+ cocoa beans is major agricultural export
+ fishing assumed great importance as a food source, domestic catching supplies more than half of the demand
+ Most of the food items and manufactured goods are in open market stalls, and streets
** Fuel
+ resource extraction is the most important sector of economy
+ crude oil, natural gas, coal, tin, columbite, petroleum -> member of OPEC (Organization of the Petroleum Exporting Countries)
** Renewable energy
+ nigeria has good solar energy generation, the most extensive of the underutilized renewable resources
** Tourism
+ Miles of coastal beaches, wildfire reserves, culture, museums with artistic trasures
+ Media portrait of country's violence disrupted tourism
** Banks
+ Naira has been devalued many times since 1980.
+ Banks proliferated in 1980s, after financial sector liberalized, but they were unstable
+ 1995 government was force to rescue them, and privatize some
+ Beggining of 21st century, the country had 100 banks and financial institutions
+ government income: petroleum royalties, rents, import duties, corporate income, value-added taxes
** Women
+ In sourthern nigeria, women do most agricultural labor
+ in lagos, women dominate the market activity
+ no legalities to exclude women from universities and professions, except in islamic controlled states
