#+TITLE: Socilogia 3
#+DESCRIPTION: Sociologia 3 - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* 05/07

#+ATTR_HTML: alt: Modelo padrão :title Modelo Padrão :style float:left;margin-bottom:20px;margin-left: auto;margin-right: auto;background-color: mintcream;display: block;max-width: 100%;height: auto;
https://luispengler.github.io/virtual-notebook/12th-grade/doc/quadroinicialsocilogia3.png

* 12/07
** Sociologia do trabalho
+ Émile Durkheim: (funcionalista): Divisão sociall do trabalho é um fato social presente em todo tipo de sociedade. Há sociedades com maior ou menor divisão social do trabalho, mas em todas elas são encontradas funções diferenciadas entre os indivíduos. Na sociedade capitalista o trabalho é pensado como uma atividade fundamental, que é exercida pelos trabalhadores. Livro: "A divisão social do trabalho".

+ Max Weber: Para esse autor, não há algo em comum ou geral em todas as sociedades, pois cada sociedade obedece a sua situação histórica exclusiva. Livro: "A ética protestante e o espírito do"

+ Karl Marx: O trabalho é visto como a essência do ser humano, existindo dois tipos de trabalho: TRABALHO CONCRETO (valor de uso) X TRABALHO ABSTRATO (valor de troca)

* 19/07
+ Para Marx, o trabalho é a essência humana e o trabalho abstrato seria alienação
+
