#+TITLE: Evolução das ideias da Física
#+DESCRIPTION: Evolução das ideias da Física - Meu caderno virtual
#+SETUPFILE: https://luispengler.github.io/site/org-html-themes/org/theme-readtheorg.setup
#+LaTeX_+HEADER: \usepackage{physics}
#+LaTeX_+HEADER: \usepackage{amsmath}
#+OPTIONS: num:nil ^:{} toc:2

* Introdução
** Avaliação
+ Livro: Origens e Evolução das ideias da física - José Fernando Rocha
+ Vai ter 2-3 páginas de resumo ao longo do curso que vai contar para N1 -> Digitado e enviado a samuel.oliveira@ufms.br
+ A N2 é um seminário sobre um tema a ser definido (previsto 21/06)
** Aula
+ Conceitos de massa, inércia e de força são simples, naturais e intuivios? Não!  (indutivo, dedutivo)
+ Hermetismo? -> philosophycal system based on the purported teachings of Hermes Trismegistus
+ Newton influenciado por conceitos de coisas que estudava (alquimia, hermetismo)
+ Palavra gravidade? (gravis) Grave, pesado, importante
* Leitura 13/03 (introdução -> pag. 36)
+ Livros criados após a segunda guerra, principalmente por autores norte-americanos traduzidos do inglês não demonstram a complexidade dos estudos de newton, principalmente dos conceitos de massa, inércia e aceleração
+ O que quer dizer a fórmula abaixo? \[f = ma\]
+ Algumas ideias modernas da ciência na verdade já estiveram no pensamento humano às vezes há milênios
+ O aprendizado da física por meio dos chamados livros-textos levam a estudantes creer que o pensamento e progresso dessa ciência se deu de forma linear, não preparando esses acadêmicos para momentos de crise científico
+ A palavra Mecânica significa a arte de construir uma máquina
#+BEGIN_QUOTE
A mecânica se entrelaça fortemente com atividades extracientíficas e sociais, como o comércio, as guerras, a mitologia e a religião
#+END_QUOTE

* Segunda aula
** Física: uma breve história
+ Na antiguidade, grandes ideias visavam resolver problemas de ordem prática
+ De primatas a astronautas: a jornada do homem em busca do conhecimento

* Leitura 15/03 (pag. 36 - 48)
#+BEGIN_QUOTE
Somente a partir do século V, com os primeiros filósofos gregos, chamados de pré-socráticos, a visão mítica e cosmogônica foi sendo substituída pelo pensamento filosófico que evoluiu, por sua vez, para uma abordagem científica da realidade: a cosmologia e a mitologia dos povos antigos foram assim as ideias embrionárias que, lentamente, ao longo de milênios, evoluíram para dar origem à Cosmologia, à Mecânica e à Física..
#+END_QUOTE
+ Um mito cosmogônico é um história transmitida de geração em geração que contava como o universo foi criado por uma ou mais entidades sobrenaturais
+ Mesopotâmia significa terra entre rios, sendo essa terra hoje em dia o iraque, situado entre os rios Tigre e Eufrates
+ Antigos hebreus (hoje em dia também chamados de judeus ou israelitas) escreveram a parte inicial da bíblia, o pentateuco ou Torá, que possui cinco livros: Gênesis, Exodus, Deuteronômio, Numerus, Levíticus
+ A escolástica medival tentava conciliar a bíblia com a Filosofia platônica e aristotélica e para isso foram responsáveis muitos pensadores, dentre eles Agostinho, Tomás de Aquino, Maimonides, Averrois
+ O capítulo quatro ainda termina descrevendo um pouco da importância para a astronomia, matemática, mecânica e física de povos como os babilônios, egípcios e chineses
